// Auto-generated from endpoint Route constants — do not edit
export const routes = {
  backgroundJobs: {
    api: {
      cancel: (id: string | number) => `/api/jobs/${id}/cancel`,
      deleteRecurring: (id: string | number) => `/api/jobs/recurring/${id}`,
      getAll: () => '/api/jobs' as const,
      getById: (id: string | number) => `/api/jobs/${id}`,
      getRecurring: () => '/api/jobs/recurring' as const,
      retry: (id: string | number) => `/api/jobs/${id}/retry`,
      toggleRecurring: (id: string | number) => `/api/jobs/recurring/${id}/toggle`,
    },
    views: {
      dashboard: () => '/admin/jobs' as const,
      detail: (id: string | number) => `/admin/jobs/${id}`,
      list: () => '/admin/jobs/list' as const,
      recurring: () => '/admin/jobs/recurring' as const,
    },
  },
  dashboard: {
    views: {
      home: () => '/' as const,
    },
  },
  featureFlags: {
    api: {
      check: (name: string | number) => `/api/feature-flags/check/${name}`,
      deleteOverride: (id: string | number) => `/api/feature-flags/overrides/${id}`,
      getAll: () => '/api/feature-flags' as const,
      getOverrides: (name: string | number) => `/api/feature-flags/${name}/overrides`,
      setOverride: (name: string | number) => `/api/feature-flags/${name}/overrides`,
      update: (name: string | number) => `/api/feature-flags/${name}`,
    },
    views: {
      manage: () => '/feature-flags' as const,
    },
  },
  fileStorage: {
    api: {
      delete: (id: string | number) => `/api/files/${id}`,
      download: (id: string | number) => `/api/files/${id}/download`,
      getAll: () => '/api/files' as const,
      getById: (id: string | number) => `/api/files/${id}`,
      listFolders: () => '/api/files/folders' as const,
      upload: () => '/api/files' as const,
    },
    views: {
      browse: () => '/files/browse' as const,
    },
  },
  marketplace: {
    api: {
      getById: (id: string | number) => `/api/marketplace/${id}`,
      search: () => '/api/marketplace' as const,
    },
    views: {
      browse: () => '/marketplace/browse' as const,
      detail: (id: string | number) => `/marketplace/${id}`,
    },
  },
  pageBuilder: {
    api: {
      create: () => '/api/pagebuilder' as const,
      delete: (id: string | number) => `/api/pagebuilder/${id}`,
      getAll: () => '/api/pagebuilder' as const,
      getById: (id: string | number) => `/api/pagebuilder/${id}`,
      permanentDelete: (id: string | number) => `/api/pagebuilder/${id}/permanent`,
      publish: (id: string | number) => `/api/pagebuilder/${id}/publish`,
      restore: (id: string | number) => `/api/pagebuilder/${id}/restore`,
      trash: () => '/api/pagebuilder/trash' as const,
      unpublish: (id: string | number) => `/api/pagebuilder/${id}/unpublish`,
      updateContent: (id: string | number) => `/api/pagebuilder/${id}/content`,
      update: (id: string | number) => `/api/pagebuilder/${id}`,
      addTagToPage: (id: string | number) => `/api/pagebuilder/${id}/tags`,
      getAllTags: () => '/api/pagebuilder/tags' as const,
      removeTagFromPage: (id: string | number, tagId: string | number) => `/api/pagebuilder/${id}/tags/${tagId}`,
      createTemplate: () => '/api/pagebuilder/templates' as const,
      deleteTemplate: (id: string | number) => `/api/pagebuilder/templates/${id}`,
      getAllTemplates: () => '/api/pagebuilder/templates' as const,
    },
    views: {
      editor: () => '/pages/new' as const,
      manage: () => '/pages/manage' as const,
      pagesList: () => '/pages' as const,
      viewerDraft: (slug: string | number) => `/pages/view/${slug}/draft`,
      viewer: (slug: string | number) => `/pages/view/${slug}`,
    },
  },
  products: {
    api: {
      create: () => '/api/products' as const,
      delete: (id: string | number) => `/api/products/${id}`,
      getAll: () => '/api/products' as const,
      getById: (id: string | number) => `/api/products/${id}`,
      update: (id: string | number) => `/api/products/${id}`,
    },
    views: {
      browse: () => '/products/browse' as const,
      create: () => '/products/create' as const,
      edit: (id: string | number) => `/products/${id}/edit`,
      manage: () => '/products/manage' as const,
    },
  },
  rateLimiting: {
    api: {
      create: () => '/api/rate-limiting' as const,
      delete: (id: string | number) => `/api/rate-limiting/${id}`,
      getActivePolicies: () => '/api/rate-limiting/active' as const,
      getAll: () => '/api/rate-limiting' as const,
      getById: (id: string | number) => `/api/rate-limiting/${id}`,
      update: (id: string | number) => `/api/rate-limiting/${id}`,
    },
    views: {
      admin: () => '/rate-limiting' as const,
    },
  },
  settings: {
    api: {
      clearHomePage: () => '/api/settings/menus/home' as const,
      createMenuItem: () => '/api/settings/menus' as const,
      deleteMenuItem: (id: string | number) => `/api/settings/menus/${id}`,
      getAvailablePages: () => '/api/settings/menus/available-pages' as const,
      getMenuTree: () => '/api/settings/menus' as const,
      reorderMenuItems: () => '/api/settings/menus/reorder' as const,
      setHomePage: (id: string | number) => `/api/settings/menus/${id}/home`,
      updateMenuItem: (id: string | number) => `/api/settings/menus/${id}`,
      deleteSetting: (key: string | number) => `/api/settings/${key}`,
      getDefinitions: () => '/api/settings/definitions' as const,
      getSetting: (key: string | number) => `/api/settings/${key}`,
      getSettings: () => '/api/settings' as const,
      updateSetting: () => '/api/settings' as const,
      deleteMySetting: (key: string | number) => `/api/settings/me/${key}`,
      getMySettings: () => '/api/settings/me' as const,
      updateMySetting: () => '/api/settings/me' as const,
    },
    views: {
      adminSettings: () => '/settings' as const,
      menuManager: () => '/settings/menus' as const,
      userSettings: () => '/settings/me' as const,
    },
  },
  tenants: {
    api: {
      deleteTenantFeature: (id: string | number, flagName: string | number) => `/api/tenants/${id}/features/${flagName}`,
      getTenantFeatures: (id: string | number) => `/api/tenants/${id}/features`,
      setTenantFeature: (id: string | number, flagName: string | number) => `/api/tenants/${id}/features/${flagName}`,
      addHost: (id: string | number) => `/api/tenants/${id}/hosts`,
      changeStatus: (id: string | number) => `/api/tenants/${id}/status`,
      create: () => '/api/tenants' as const,
      delete: (id: string | number) => `/api/tenants/${id}`,
      getAll: () => '/api/tenants' as const,
      getById: (id: string | number) => `/api/tenants/${id}`,
      removeHost: (id: string | number, hostId: string | number) => `/api/tenants/${id}/hosts/${hostId}`,
      update: (id: string | number) => `/api/tenants/${id}`,
    },
    views: {
      browse: () => '/tenants/browse' as const,
      create: () => '/tenants/create' as const,
      edit: (id: string | number) => `/tenants/${id}/edit`,
      features: (id: string | number) => `/tenants/${id}/features`,
      manage: () => '/tenants/manage' as const,
    },
  },
  auditLogs: {
    api: {
      export: () => '/api/audit-logs/export' as const,
      getAll: () => '/api/audit-logs' as const,
      getById: (id: string | number) => `/api/audit-logs/${id}`,
      getStats: () => '/api/audit-logs/stats' as const,
    },
    views: {
      browse: () => '/audit-logs/browse' as const,
      dashboard: () => '/audit-logs/dashboard' as const,
      detail: (id: string | number) => `/audit-logs/${id}`,
    },
  },
  users: {
    api: {
      accountSecurity: () => '/Manage/TwoFactorAuthentication' as const,
      create: () => '/api/users/' as const,
      delete: (id: string | number) => `/api/users/${id}`,
      downloadPersonalData: () => '/api/users/download-personal-data' as const,
      getAll: () => '/api/users/' as const,
      getById: (id: string | number) => `/api/users/${id}`,
      getCurrent: () => '/api/users/me' as const,
      update: (id: string | number) => `/api/users/${id}`,
    },
    views: {
      accessDenied: () => '/Identity/Account/AccessDenied' as const,
      confirmEmailChange: () => '/Identity/Account/ConfirmEmailChange' as const,
      confirmEmail: () => '/Identity/Account/ConfirmEmail' as const,
      disable2fa: () => '/Identity/Account/Manage/Disable2fa' as const,
      enableAuthenticator: () => '/Identity/Account/Manage/EnableAuthenticator' as const,
      error: () => '/Identity/Account/Error' as const,
      externalLogin: () => '/Identity/Account/ExternalLogin' as const,
      forgotPasswordConfirmation: () => '/Identity/Account/ForgotPasswordConfirmation' as const,
      forgotPassword: () => '/Identity/Account/ForgotPassword' as const,
      generateRecoveryCodes: () => '/Identity/Account/Manage/GenerateRecoveryCodes' as const,
      lockout: () => '/Identity/Account/Lockout' as const,
      login: () => '/Identity/Account/Login' as const,
      loginWith2fa: () => '/Identity/Account/LoginWith2fa' as const,
      loginWithRecoveryCode: () => '/Identity/Account/LoginWithRecoveryCode' as const,
      logout: () => '/Identity/Account/Logout' as const,
      registerConfirmation: () => '/Identity/Account/RegisterConfirmation' as const,
      register: () => '/Identity/Account/Register' as const,
      resendEmailConfirmation: () => '/Identity/Account/ResendEmailConfirmation' as const,
      resetAuthenticator: () => '/Identity/Account/Manage/ResetAuthenticator' as const,
      resetPasswordConfirmation: () => '/Identity/Account/ResetPasswordConfirmation' as const,
      resetPassword: () => '/Identity/Account/ResetPassword' as const,
      twoFactorAuthentication: () => '/Identity/Account/Manage/TwoFactorAuthentication' as const,
      changePassword: () => '/Identity/Account/Manage/ChangePassword' as const,
      deletePersonalData: () => '/Identity/Account/Manage/DeletePersonalData' as const,
      email: () => '/Identity/Account/Manage/Email' as const,
      externalLogins: () => '/Identity/Account/Manage/ExternalLogins' as const,
      manageIndex: () => '/Identity/Account/Manage' as const,
      personalData: () => '/Identity/Account/Manage/PersonalData' as const,
      setPassword: () => '/Identity/Account/Manage/SetPassword' as const,
    },
  },
  email: {
    api: {
      getAllMessages: () => '/api/email/messages' as const,
      getMessageById: (id: string | number) => `/api/email/messages/${id}`,
      sendEmail: () => '/api/email/messages/send' as const,
      getStats: () => '/api/email/stats' as const,
      createTemplate: () => '/api/email/templates' as const,
      deleteTemplate: (id: string | number) => `/api/email/templates/${id}`,
      getAllTemplates: () => '/api/email/templates' as const,
      getTemplateById: (id: string | number) => `/api/email/templates/${id}`,
      updateTemplate: (id: string | number) => `/api/email/templates/${id}`,
    },
    views: {
      createTemplate: () => '/email/templates/create' as const,
      dashboard: () => '/email/dashboard' as const,
      editTemplate: (id: string | number) => `/email/templates/${id}/edit`,
      history: () => '/email/history' as const,
      settings: () => '/email/settings' as const,
      templates: () => '/email/templates' as const,
    },
  },
  orders: {
    api: {
      create: () => '/api/orders' as const,
      delete: (id: string | number) => `/api/orders/${id}`,
      getAll: () => '/api/orders' as const,
      getById: (id: string | number) => `/api/orders/${id}`,
      update: (id: string | number) => `/api/orders/${id}`,
    },
    views: {
      create: () => '/orders/create' as const,
      edit: (id: string | number) => `/orders/${id}/edit`,
      list: () => '/orders' as const,
    },
  },
  openIddict: {
    api: {
      authorization: () => '/connect/authorize' as const,
      logout: () => '/connect/endsession' as const,
      token: () => '/connect/token' as const,
      userinfo: () => '/connect/userinfo' as const,
    },
    views: {
      clientsCreate: () => '/openiddict/clients/create' as const,
      clientsEdit: (id: string | number) => `/openiddict/clients/${id}/edit`,
      clients: () => '/openiddict/clients' as const,
    },
  },
  admin: {
    api: {
      adminRoles: () => '/admin/roles' as const,
      adminSessions: (id: string | number, tokenId: string | number) => `/admin/users/${id}/sessions/${tokenId}`,
      adminUsers: () => '/admin/users' as const,
    },
    views: {
      rolesCreate: () => '/admin/roles/create' as const,
      rolesEdit: (id: string | number) => `/admin/roles/${id}/edit`,
      roles: () => '/admin/roles' as const,
      usersCreate: () => '/admin/users/create' as const,
      usersEdit: (id: string | number) => `/admin/users/${id}/edit`,
      users: () => '/admin/users' as const,
    },
  },
} as const;

