using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

[Generator]
public class ModuleDiscovererGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new ModuleSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not ModuleSyntaxReceiver receiver)
            return;

        var modules = receiver.Modules;
        if (modules.Count == 0)
            return;

        // Generate service registration
        var serviceSource = new StringBuilder();
        serviceSource.AppendLine("// <auto-generated/>");
        serviceSource.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        serviceSource.AppendLine("using SimpleModule.Core;");
        serviceSource.AppendLine();
        serviceSource.AppendLine("namespace SimpleModule.Core;");
        serviceSource.AppendLine();
        serviceSource.AppendLine("public static class ModuleExtensions");
        serviceSource.AppendLine("{");
        serviceSource.AppendLine("    public static IServiceCollection AddModules(this IServiceCollection services)");
        serviceSource.AppendLine("    {");

        foreach (var module in modules)
        {
            serviceSource.AppendLine($"        services.AddScoped<IModule, {module}>();");
        }

        serviceSource.AppendLine("        return services;");
        serviceSource.AppendLine("    }");
        serviceSource.AppendLine("}");

        context.AddSource("ModuleExtensions.g.cs", SourceText.From(serviceSource.ToString(), Encoding.UTF8));

        // Generate endpoint registration
        var endpointSource = new StringBuilder();
        endpointSource.AppendLine("// <auto-generated/>");
        endpointSource.AppendLine("using Microsoft.AspNetCore.Builder;");
        endpointSource.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        endpointSource.AppendLine("using SimpleModule.Core;");
        endpointSource.AppendLine();
        endpointSource.AppendLine("namespace SimpleModule.Core;");
        endpointSource.AppendLine();
        endpointSource.AppendLine("public static class EndpointExtensions");
        endpointSource.AppendLine("{");
        endpointSource.AppendLine("    public static WebApplication MapModuleEndpoints(this WebApplication app)");
        endpointSource.AppendLine("    {");
        endpointSource.AppendLine("        var modules = app.Services.GetServices<IModule>();");
        endpointSource.AppendLine("        foreach (var module in modules)");
        endpointSource.AppendLine("        {");
        endpointSource.AppendLine("            module.ConfigureEndpoints(app);");
        endpointSource.AppendLine("        }");
        endpointSource.AppendLine("        return app;");
        endpointSource.AppendLine("    }");
        endpointSource.AppendLine("}");

        context.AddSource("EndpointExtensions.g.cs", SourceText.From(endpointSource.ToString(), Encoding.UTF8));
    }
}

public class ModuleSyntaxReceiver : ISyntaxReceiver
{
    public List<string> Modules { get; } = new();

    public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
    {
        if (syntaxNode is ClassDeclarationSyntax classDeclaration &&
            classDeclaration.AttributeLists.Count > 0)
        {
            foreach (var attributeList in classDeclaration.AttributeLists)
            {
                foreach (var attribute in attributeList.Attributes)
                {
                    if (attribute.Name.ToString() == "Module")
                    {
                        Modules.Add(classDeclaration.Identifier.Text);
                    }
                }
            }
        }
    }
} 