using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

[Generator]
public class ModuleDiscovererGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use compilation to find all types with [Module] attribute across all referenced assemblies
        var compilationProvider = context.CompilationProvider;

        context.RegisterSourceOutput(
            compilationProvider,
            static (spc, compilation) =>
            {
                var moduleAttributeSymbol = compilation.GetTypeByMetadataName(
                    "SimpleModule.Core.ModuleAttribute"
                );
                var moduleInterfaceSymbol = compilation.GetTypeByMetadataName(
                    "SimpleModule.Core.IModule"
                );

                if (moduleAttributeSymbol is null || moduleInterfaceSymbol is null)
                    return;

                var modules = new List<string>();

                // Search all referenced assemblies for types with [Module] attribute
                foreach (var reference in compilation.References)
                {
                    var assemblySymbol =
                        compilation.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
                    if (assemblySymbol is null)
                        continue;

                    FindModuleTypes(assemblySymbol.GlobalNamespace, moduleAttributeSymbol, modules);
                }

                // Also search the current compilation's assembly
                FindModuleTypes(
                    compilation.Assembly.GlobalNamespace,
                    moduleAttributeSymbol,
                    modules
                );

                if (modules.Count == 0)
                    return;

                GenerateModuleExtensions(spc, modules);
                GenerateEndpointExtensions(spc, modules);
            }
        );
    }

    private static void FindModuleTypes(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol moduleAttributeSymbol,
        List<string> modules
    )
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol childNamespace)
            {
                FindModuleTypes(childNamespace, moduleAttributeSymbol, modules);
            }
            else if (member is INamedTypeSymbol typeSymbol)
            {
                foreach (var attr in typeSymbol.GetAttributes())
                {
                    if (
                        SymbolEqualityComparer.Default.Equals(
                            attr.AttributeClass,
                            moduleAttributeSymbol
                        )
                    )
                    {
                        modules.Add(
                            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                        );
                        break;
                    }
                }
            }
        }
    }

    private static void GenerateModuleExtensions(
        SourceProductionContext context,
        List<string> modules
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class ModuleExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static IServiceCollection AddModules(this IServiceCollection services)"
        );
        sb.AppendLine("    {");

        foreach (var module in modules)
        {
            sb.AppendLine($"        new {module}().ConfigureServices(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ModuleExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateEndpointExtensions(
        SourceProductionContext context,
        List<string> modules
    )
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static WebApplication MapModuleEndpoints(this WebApplication app)"
        );
        sb.AppendLine("    {");

        foreach (var module in modules)
        {
            sb.AppendLine($"        new {module}().ConfigureEndpoints(app);");
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("EndpointExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
