export const pages: Record<string, unknown> = {
  // Auth pages
  'Users/Account/Login': () => import('./Account/Login'),
  'Users/Account/Register': () => import('./Account/Register'),
  'Users/Account/Logout': () => import('./Account/Logout'),
  'Users/Account/RegisterConfirmation': () => import('./Account/RegisterConfirmation'),
  'Users/Account/ForgotPassword': () => import('./Account/ForgotPassword'),
  'Users/Account/ForgotPasswordConfirmation': () => import('./Account/ForgotPasswordConfirmation'),
  'Users/Account/ResetPassword': () => import('./Account/ResetPassword'),
  'Users/Account/ResetPasswordConfirmation': () => import('./Account/ResetPasswordConfirmation'),
  'Users/Account/ConfirmEmail': () => import('./Account/ConfirmEmail'),
  'Users/Account/ConfirmEmailChange': () => import('./Account/ConfirmEmailChange'),
  'Users/Account/ResendEmailConfirmation': () => import('./Account/ResendEmailConfirmation'),
  'Users/Account/LoginWith2fa': () => import('./Account/LoginWith2fa'),
  'Users/Account/LoginWithRecoveryCode': () => import('./Account/LoginWithRecoveryCode'),
  'Users/Account/Lockout': () => import('./Account/Lockout'),
  'Users/Account/AccessDenied': () => import('./Account/AccessDenied'),
  'Users/Account/Error': () => import('./Account/Error'),
  'Users/Account/ExternalLogin': () => import('./Account/ExternalLogin'),
  // Manage pages
  'Users/Account/Manage/Index': () => import('./Account/Manage/ManageIndex'),
  'Users/Account/Manage/Email': () => import('./Account/Manage/Email'),
  'Users/Account/Manage/ChangePassword': () => import('./Account/Manage/ChangePassword'),
  'Users/Account/Manage/SetPassword': () => import('./Account/Manage/SetPassword'),
  'Users/Account/Manage/DeletePersonalData': () => import('./Account/Manage/DeletePersonalData'),
  'Users/Account/Manage/PersonalData': () => import('./Account/Manage/PersonalData'),
  'Users/Account/Manage/ExternalLogins': () => import('./Account/Manage/ExternalLogins'),
  'Users/Account/Manage/Passkeys': () => import('./Account/Manage/ManagePasskeys'),
  'Users/Account/TwoFactorAuthentication': () => import('./Account/TwoFactorAuthentication'),
  'Users/Account/EnableAuthenticator': () => import('./Account/EnableAuthenticator'),
  'Users/Account/Disable2fa': () => import('./Account/Disable2fa'),
  'Users/Account/ResetAuthenticator': () => import('./Account/ResetAuthenticator'),
  'Users/Account/GenerateRecoveryCodes': () => import('./Account/GenerateRecoveryCodes'),
  'Users/Account/ShowRecoveryCodes': () => import('./Account/ShowRecoveryCodes'),
};
