using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class AgentExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Core.Agents;");
        sb.AppendLine("using SimpleModule.Core.Rag;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class AgentExtensions");
        sb.AppendLine("{");

        // AddModuleAgents
        sb.AppendLine(
            "    public static IServiceCollection AddModuleAgents(this IServiceCollection services)"
        );
        sb.AppendLine("    {");

        // Register agent definitions
        foreach (var agent in data.AgentDefinitions)
        {
            sb.AppendLine($"        services.AddScoped<{agent.FullyQualifiedName}>();");
        }

        // Register tool providers
        foreach (var provider in data.AgentToolProviders)
        {
            sb.AppendLine($"        services.AddScoped<{provider.FullyQualifiedName}>();");
        }

        // Register knowledge sources
        foreach (var source in data.KnowledgeSources)
        {
            sb.AppendLine(
                $"        services.AddSingleton<global::SimpleModule.Core.Rag.IKnowledgeSource, {source.FullyQualifiedName}>();"
            );
        }

        sb.AppendLine();

        // Build agent registry
        sb.AppendLine("        var registry = new global::SimpleModule.Agents.AgentRegistry();");

        // Group tool providers by module
        var providersByModule = new Dictionary<string, List<string>>();
        foreach (var provider in data.AgentToolProviders)
        {
            if (!providersByModule.TryGetValue(provider.ModuleName, out var list))
            {
                list = new List<string>();
                providersByModule[provider.ModuleName] = list;
            }

            list.Add(provider.FullyQualifiedName);
        }

        foreach (var agent in data.AgentDefinitions)
        {
            var toolProviderTypes = providersByModule.TryGetValue(
                agent.ModuleName,
                out var providers
            )
                ? string.Join(", ", providers.Select(p => $"typeof({p})"))
                : "";

            // Instantiate once and read both properties from the same instance
            var varName =
                "_agent_"
                + agent.ModuleName
                + "_"
                + agent
                    .FullyQualifiedName.GetHashCode()
                    .ToString("x8", System.Globalization.CultureInfo.InvariantCulture);
            sb.AppendLine(
                $"        var {varName} = (global::SimpleModule.Core.Agents.IAgentDefinition)new {agent.FullyQualifiedName}();"
            );
            sb.AppendLine(
                $"        registry.Register(new global::SimpleModule.Agents.AgentRegistration("
            );
            sb.AppendLine($"            {varName}.Name,");
            sb.AppendLine($"            {varName}.Description,");
            sb.AppendLine($"            \"{agent.ModuleName}\",");
            sb.AppendLine($"            typeof({agent.FullyQualifiedName}),");

            if (!string.IsNullOrEmpty(toolProviderTypes))
            {
                sb.AppendLine($"            new System.Type[] {{ {toolProviderTypes} }}));");
            }
            else
            {
                sb.AppendLine($"            System.Array.Empty<System.Type>()));");
            }
        }

        sb.AppendLine(
            "        services.AddSingleton<global::SimpleModule.Agents.IAgentRegistry>(registry);"
        );

        // Call ConfigureAgents on modules that override it (manual escape hatch)
        var modulesWithAgents = data.Modules.Where(m => m.HasConfigureAgents).ToList();
        if (modulesWithAgents.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine(
                "        var agentBuilder = new global::SimpleModule.Agents.AgentBuilder();"
            );
            foreach (var module in modulesWithAgents)
            {
                var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
                sb.AppendLine(
                    $"        ((global::SimpleModule.Core.IModule)ModuleExtensions.{fieldName}).ConfigureAgents(agentBuilder);"
                );
            }

            // Register manually-added agents and tool providers from ConfigureAgents
            sb.AppendLine("        foreach (var agentType in agentBuilder.AgentTypes)");
            sb.AppendLine("        {");
            sb.AppendLine("            services.AddScoped(agentType);");
            sb.AppendLine("        }");
            sb.AppendLine("        foreach (var providerType in agentBuilder.ToolProviderTypes)");
            sb.AppendLine("        {");
            sb.AppendLine("            services.AddScoped(providerType);");
            sb.AppendLine("        }");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("AgentExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
