using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class AgentExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (
            data.AgentDefinitions.Length == 0
            && data.AgentToolProviders.Length == 0
            && data.KnowledgeSources.Length == 0
            && !data.Modules.Any(m => m.HasConfigureAgents)
        )
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Core.Agents;");
        sb.AppendLine("using SimpleModule.Core.Rag;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class AgentExtensions");
        sb.AppendLine("{");

        // AddModuleAgents
        sb.AppendLine(
            "    public static IServiceCollection AddModuleAgents(this IServiceCollection services)"
        );
        sb.AppendLine("    {");

        // Register agent definitions
        foreach (var agent in data.AgentDefinitions)
        {
            sb.AppendLine($"        services.AddScoped<{agent.FullyQualifiedName}>();");
        }

        // Register tool providers
        foreach (var provider in data.AgentToolProviders)
        {
            sb.AppendLine($"        services.AddScoped<{provider.FullyQualifiedName}>();");
        }

        // Register knowledge sources
        foreach (var source in data.KnowledgeSources)
        {
            sb.AppendLine(
                $"        services.AddSingleton<global::SimpleModule.Core.Rag.IKnowledgeSource, {source.FullyQualifiedName}>();"
            );
        }

        sb.AppendLine();

        // Build agent registry
        sb.AppendLine("        var registry = new global::SimpleModule.Agents.AgentRegistry();");

        // Group tool providers by module
        var providersByModule = new Dictionary<string, List<string>>();
        foreach (var provider in data.AgentToolProviders)
        {
            if (!providersByModule.TryGetValue(provider.ModuleName, out var list))
            {
                list = new List<string>();
                providersByModule[provider.ModuleName] = list;
            }

            list.Add(provider.FullyQualifiedName);
        }

        foreach (var agent in data.AgentDefinitions)
        {
            var toolProviderTypes = providersByModule.TryGetValue(
                agent.ModuleName,
                out var providers
            )
                ? string.Join(", ", providers.Select(p => $"typeof({p})"))
                : "";

            sb.AppendLine(
                $"        registry.Register(new global::SimpleModule.Agents.AgentRegistration("
            );
            sb.AppendLine(
                $"            ((global::SimpleModule.Core.Agents.IAgentDefinition)new {agent.FullyQualifiedName}()).Name,"
            );
            sb.AppendLine(
                $"            ((global::SimpleModule.Core.Agents.IAgentDefinition)new {agent.FullyQualifiedName}()).Description,"
            );
            sb.AppendLine($"            \"{agent.ModuleName}\",");
            sb.AppendLine($"            typeof({agent.FullyQualifiedName}),");

            if (!string.IsNullOrEmpty(toolProviderTypes))
            {
                sb.AppendLine($"            new System.Type[] {{ {toolProviderTypes} }}));");
            }
            else
            {
                sb.AppendLine($"            System.Array.Empty<System.Type>()));");
            }
        }

        sb.AppendLine(
            "        services.AddSingleton<global::SimpleModule.Agents.IAgentRegistry>(registry);"
        );

        // Agent permissions
        var agentModules = new HashSet<string>();
        foreach (var agent in data.AgentDefinitions)
        {
            agentModules.Add(agent.ModuleName);
        }

        if (agentModules.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine(
                "        var agentPermissionBuilder = new global::SimpleModule.Core.Authorization.PermissionRegistryBuilder();"
            );

            foreach (var moduleName in agentModules)
            {
                sb.AppendLine(
                    $"        agentPermissionBuilder.AddPermission(\"Agents.{moduleName}.Execute\");"
                );
            }

            sb.AppendLine("        agentPermissionBuilder.AddPermission(\"Agents.Execute\");");
        }

        // Call ConfigureAgents on modules that override it
        var modulesWithAgents = data.Modules.Where(m => m.HasConfigureAgents).ToList();
        if (modulesWithAgents.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine(
                "        var agentBuilder = new global::SimpleModule.Agents.AgentBuilder();"
            );
            foreach (var module in modulesWithAgents)
            {
                var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
                sb.AppendLine(
                    $"        ((global::SimpleModule.Core.IModule)ModuleExtensions.{fieldName}).ConfigureAgents(agentBuilder);"
                );
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        sb.AppendLine();

        // MapModuleAgentEndpoints
        sb.AppendLine("    public static void MapModuleAgentEndpoints(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        var registry = app.Services.GetRequiredService<global::SimpleModule.Agents.IAgentRegistry>();"
        );
        sb.AppendLine(
            "        global::SimpleModule.Agents.AgentEndpoints.MapAgentEndpoints(app, registry);"
        );
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("AgentExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
