using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

/// <summary>
/// Emits a registry of all discovered contract interfaces and their implementations.
/// This allows test infrastructure to enumerate and resolve every contract at runtime,
/// catching circular dependencies that only manifest during DI resolution.
/// </summary>
internal sealed class ContractRegistryEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.ContractImplementations.Length == 0)
            return;

        // Group by interface and only include interfaces with exactly one valid implementation
        // (matching what ModuleExtensionsEmitter actually registers with the DI container).
        var implsByInterface = new Dictionary<string, List<ContractImplementationRecord>>();
        foreach (var impl in data.ContractImplementations)
        {
            if (!impl.IsPublic || impl.IsAbstract)
                continue;

            if (!implsByInterface.TryGetValue(impl.InterfaceFqn, out var list))
            {
                list = new List<ContractImplementationRecord>();
                implsByInterface[impl.InterfaceFqn] = list;
            }
            list.Add(impl);
        }

        var singleImpls = implsByInterface
            .Where(kvp => kvp.Value.Count == 1)
            .OrderBy(kvp => kvp.Key)
            .ToArray();

        if (singleImpls.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine(
            "/// Registry of all discovered module contract interfaces that have exactly one"
        );
        sb.AppendLine(
            "/// registered implementation. Enables tests to enumerate and resolve every contract"
        );
        sb.AppendLine(
            "/// without having to hardcode the list, catching new circular dependencies as modules"
        );
        sb.AppendLine("/// are added.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ModuleContractRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static System.Type[] All { get; } = new System.Type[]");
        sb.AppendLine("    {");

        foreach (var kvp in singleImpls)
        {
            sb.AppendLine($"        typeof({kvp.Key}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("ContractRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
