using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class DbContextRegistryEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.DbContexts.Length == 0)
            return;

        var sorted = data.DbContexts.OrderBy(c => c.ModuleName).ToArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class ModuleDbContextRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static System.Type[] All { get; } = new System.Type[]");
        sb.AppendLine("    {");

        foreach (var ctx in sorted)
        {
            sb.AppendLine($"        typeof({ctx.FullyQualifiedName}),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource(
            "DbContextRegistry.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
