using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class EndpointExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = TopologicalSort.SortModules(data);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using SimpleModule.Core.Authorization;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class EndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static WebApplication MapModuleEndpoints(this WebApplication app)"
        );
        sb.AppendLine("    {");

        // Auto-registered endpoints (IEndpoint implementors)
        // Skip modules that define ConfigureEndpoints — they manage their own registration.
        foreach (var module in modules)
        {
            if (module.Endpoints.Length == 0 || module.HasConfigureEndpoints)
                continue;

            sb.AppendLine();
            sb.AppendLine($"        // Auto-registered endpoints for {module.FullyQualifiedName}");
            sb.AppendLine("        {");

            if (!string.IsNullOrEmpty(module.RoutePrefix))
            {
                sb.AppendLine(
                    $"            var group = app.MapGroup(\"{module.RoutePrefix}\").WithTags(\"{module.ModuleName}\").RequireAuthorization();"
                );
                foreach (var endpoint in module.Endpoints)
                {
                    EmitEndpointRegistration(sb, endpoint, "group");
                }
            }
            else
            {
                foreach (var endpoint in module.Endpoints)
                {
                    EmitEndpointRegistration(sb, endpoint, "app");
                }
            }

            sb.AppendLine("        }");
        }

        // Auto-registered view endpoints (IViewEndpoint implementors)
        foreach (var module in modules)
        {
            if (module.Views.Length == 0)
                continue;

            sb.AppendLine();
            sb.AppendLine(
                $"        // Auto-registered view endpoints for {module.FullyQualifiedName}"
            );
            sb.AppendLine("        {");

            if (!string.IsNullOrEmpty(module.ViewPrefix))
            {
                sb.AppendLine(
                    $"            var viewGroup = app.MapGroup(\"{module.ViewPrefix}\").WithTags(\"{module.ModuleName}\").ExcludeFromDescription().RequireAuthorization();"
                );
                foreach (var view in module.Views)
                {
                    sb.AppendLine($"            new {view.FullyQualifiedName}().Map(viewGroup);");
                }
            }
            else
            {
                foreach (var view in module.Views)
                {
                    sb.AppendLine($"            new {view.FullyQualifiedName}().Map(app);");
                }
            }

            sb.AppendLine("        }");
        }

        // Manual ConfigureEndpoints (escape hatch)
        foreach (var module in modules.Where(m => m.HasConfigureEndpoints))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine();
            sb.AppendLine(
                $"        ((global::SimpleModule.Core.IModule)ModuleExtensions.{fieldName}).ConfigureEndpoints(app);"
            );
        }

        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("EndpointExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits endpoint registration with authorization enforcement based on discovered attributes.
    /// If the endpoint has [AllowAnonymous] or [RequirePermission], wraps it in a sub-group
    /// to apply the policy without changing the IEndpoint.Map() return type (non-breaking).
    /// </summary>
    private static void EmitEndpointRegistration(
        StringBuilder sb,
        EndpointInfoRecord endpoint,
        string routeBuilder
    )
    {
        if (endpoint.AllowAnonymous)
        {
            sb.AppendLine(
                $"            {{ var _eg = {routeBuilder}.MapGroup(\"\"); _eg.AllowAnonymous(); new {endpoint.FullyQualifiedName}().Map(_eg); }}"
            );
        }
        else if (endpoint.RequiredPermissions.Length > 0)
        {
            var perms = string.Join("\", \"", endpoint.RequiredPermissions);
            sb.AppendLine(
                $"            {{ var _eg = {routeBuilder}.MapGroup(\"\"); _eg.RequirePermission(\"{perms}\"); new {endpoint.FullyQualifiedName}().Map(_eg); }}"
            );
        }
        else
        {
            sb.AppendLine($"            new {endpoint.FullyQualifiedName}().Map({routeBuilder});");
        }
    }
}
