using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

/// <summary>
/// Emits AddSimpleModule() and UseSimpleModule() extension methods that compose
/// the infrastructure methods from SimpleModule.Hosting with source-generated
/// module registration and endpoint mapping.
/// </summary>
internal sealed class HostingExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modulesWithMiddleware = data.Modules.Where(m => m.HasConfigureMiddleware).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Core;");
        sb.AppendLine("using SimpleModule.Core.Inertia;");
        sb.AppendLine("using SimpleModule.Core.Menu;");
        sb.AppendLine("using SimpleModule.Database;");
        sb.AppendLine("using SimpleModule.Hosting;");
        sb.AppendLine("using SimpleModule.Host;");
        sb.AppendLine("using SimpleModule.Host.Components;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Hosting;");
        sb.AppendLine();
        sb.AppendLine("public static class SimpleModuleExtensions");
        sb.AppendLine("{");

        // AddSimpleModule
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Registers all SimpleModule services: infrastructure, modules, database, menus, settings, and pages."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static WebApplicationBuilder AddSimpleModule(");
        sb.AppendLine("        this WebApplicationBuilder builder,");
        sb.AppendLine("        System.Action<SimpleModuleOptions>? configure = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.AddSimpleModuleInfrastructure(o =>");
        sb.AppendLine("        {");
        sb.AppendLine("            o.ShellComponent ??= typeof(InertiaShell);");
        sb.AppendLine("            configure?.Invoke(o);");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        // Source-generated module registration");
        sb.AppendLine("        builder.Services.AddModules(builder.Configuration);");
        sb.AppendLine();
        sb.AppendLine(
            "        builder.Services.AddModuleDbContext<HostDbContext>(builder.Configuration, global::SimpleModule.Database.DatabaseConstants.HostModuleName);"
        );
        sb.AppendLine();
        sb.AppendLine("        builder.Services.CollectModuleMenuItems();");
        sb.AppendLine("        builder.Services.CollectModuleSettings();");
        sb.AppendLine(
            "        builder.Services.AddSingleton<System.Collections.Generic.IReadOnlyList<AvailablePage>>(PageRegistry.Pages);"
        );
        sb.AppendLine();
        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // UseSimpleModule
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Configures the SimpleModule middleware pipeline and maps all module endpoints."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    public static async System.Threading.Tasks.Task<WebApplication> UseSimpleModule(this WebApplication app)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        await app.UseSimpleModuleInfrastructure();");

        if (modulesWithMiddleware.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("        // Module middleware");
            foreach (var module in modulesWithMiddleware)
            {
                var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
                sb.AppendLine(
                    $"        ((global::SimpleModule.Core.IModule)ModuleExtensions.{fieldName}).ConfigureMiddleware(app);"
                );
            }
        }

        sb.AppendLine();
        sb.AppendLine("        // Source-generated component and endpoint mapping");
        sb.AppendLine("        app.MapRazorComponents<App>().AddModuleAssemblies();");
        sb.AppendLine("        app.MapModuleEndpoints();");
        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        context.AddSource("HostingExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
