using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class HostDbContextEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.DbContexts.Length == 0)
            return;

        // Abort if any error-level diagnostics were reported (SM0003, SM0005, SM0007)
        var identityCount = 0;
        var hasBadIdentityArgs = false;
        foreach (var ctx in data.DbContexts)
        {
            if (ctx.IsIdentityDbContext)
            {
                identityCount++;
                if (string.IsNullOrEmpty(ctx.IdentityUserTypeFqn))
                    hasBadIdentityArgs = true;
            }
        }

        var hasDuplicateConfigs = false;
        var configEntities = new System.Collections.Generic.HashSet<string>();
        foreach (var config in data.EntityConfigs)
        {
            if (!configEntities.Add(config.EntityFqn))
                hasDuplicateConfigs = true;
        }

        if (identityCount > 1 || hasBadIdentityArgs || hasDuplicateConfigs)
            return;

        // Determine if any module uses IdentityDbContext
        DbContextInfoRecord? identityContext = null;
        foreach (var ctx in data.DbContexts)
        {
            if (ctx.IsIdentityDbContext)
            {
                identityContext = ctx;
                break;
            }
        }

        // Collect all DbSet<T> across modules, deduplicated by entity FQN
        var seenEntities = new System.Collections.Generic.HashSet<string>();
        var allDbSets = new System.Collections.Generic.List<(
            string PropertyName,
            string EntityFqn,
            string ModuleName
        )>();
        foreach (var ctx in data.DbContexts)
        {
            foreach (var dbSet in ctx.DbSets)
            {
                if (seenEntities.Add(dbSet.EntityFqn))
                {
                    allDbSets.Add((dbSet.PropertyName, dbSet.EntityFqn, ctx.ModuleName));
                }
            }
        }

        // Check for duplicate DbSet property names across modules
        var propertyNameOwners = new System.Collections.Generic.Dictionary<
            string,
            (string EntityFqn, string ModuleName)
        >();
        var hasDuplicates = false;
        foreach (var entry in allDbSets)
        {
            if (propertyNameOwners.TryGetValue(entry.PropertyName, out var existing))
            {
                // Same entity type with same property name is fine (deduplicated earlier)
                if (existing.EntityFqn != entry.EntityFqn)
                {
                    // Find the DbContext location for the conflicting module
                    SourceLocationRecord? dbCtxLoc = null;
                    foreach (var ctx in data.DbContexts)
                    {
                        if (ctx.ModuleName == entry.ModuleName)
                        {
                            dbCtxLoc = ctx.Location;
                            break;
                        }
                    }

                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DiagnosticDescriptors.DuplicateDbSetPropertyName,
                            LocationHelper.ToLocation(dbCtxLoc),
                            entry.PropertyName,
                            existing.ModuleName,
                            TypeMappingHelpers.StripGlobalPrefix(existing.EntityFqn),
                            entry.ModuleName,
                            TypeMappingHelpers.StripGlobalPrefix(entry.EntityFqn)
                        )
                    );
                    hasDuplicates = true;
                }
            }
            else
            {
                propertyNameOwners[entry.PropertyName] = (entry.EntityFqn, entry.ModuleName);
            }
        }

        if (hasDuplicates)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using SimpleModule.Database;");

        if (identityContext != null)
        {
            sb.AppendLine("using Microsoft.AspNetCore.Identity.EntityFrameworkCore;");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {data.HostAssemblyName};");
        sb.AppendLine();

        // Class declaration with primary constructor
        if (identityContext != null)
        {
            sb.AppendLine($"public partial class HostDbContext(");
            sb.AppendLine("    DbContextOptions<HostDbContext> options,");
            sb.AppendLine("    IOptions<DatabaseOptions> dbOptions");
            sb.AppendLine($") : IdentityDbContext<{identityContext.Value.IdentityUserTypeFqn},");
            sb.AppendLine($"                      {identityContext.Value.IdentityRoleTypeFqn},");
            sb.AppendLine(
                $"                      {identityContext.Value.IdentityKeyTypeFqn}>(options)"
            );
        }
        else
        {
            // Always partial: ValueConverterConventionsEmitter contributes a
            // partial ConfigureConventions whenever Vogen value objects exist,
            // independent of whether an Identity context is present (CS0260
            // in non-identity hosts otherwise).
            sb.AppendLine("public partial class HostDbContext(");
            sb.AppendLine("    DbContextOptions<HostDbContext> options,");
            sb.AppendLine("    IOptions<DatabaseOptions> dbOptions");
            sb.AppendLine(") : DbContext(options)");
        }

        sb.AppendLine("{");

        // DbSet properties
        foreach (var dbSet in allDbSets)
        {
            sb.AppendLine($"    public DbSet<{dbSet.EntityFqn}> {dbSet.PropertyName}");
            sb.AppendLine($"        => Set<{dbSet.EntityFqn}>();");
            sb.AppendLine();
        }

        // OnModelCreating
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder builder)");
        sb.AppendLine("    {");

        if (identityContext != null)
        {
            sb.AppendLine("        base.OnModelCreating(builder);");
            sb.AppendLine();
        }

        // Apply IEntityTypeConfiguration<T> implementations
        if (data.EntityConfigs.Length > 0)
        {
            sb.AppendLine(
                "        // Apply IEntityTypeConfiguration<T> found in module assemblies"
            );
            foreach (var config in data.EntityConfigs)
            {
                sb.AppendLine($"        builder.ApplyConfiguration(new {config.ConfigFqn}());");
            }
            sb.AppendLine();
        }

        // Schema isolation. Each entity is attributed to its owning module — by table-name
        // prefix on SQLite, by schema on PostgreSQL/SQL Server. The runtime helper resolves
        // navigation-reachable child entities (which have no DbSet of their own) to the module
        // of the principal they relate to, and sweeps any remaining entities (e.g. ASP.NET
        // Identity tables) into the identity module. See ApplyHostModuleSchemas (#229).
        sb.AppendLine(
            "        // Module schema isolation: prefix (SQLite) or schema (PostgreSQL/SQL Server)"
        );
        sb.AppendLine(
            "        var moduleByEntityType = new global::System.Collections.Generic.Dictionary<global::System.Type, string>"
        );
        sb.AppendLine("        {");
        foreach (var entry in allDbSets)
        {
            sb.AppendLine($"            [typeof({entry.EntityFqn})] = \"{entry.ModuleName}\",");
        }
        sb.AppendLine("        };");

        var identityModuleArg =
            identityContext != null ? $"\"{identityContext.Value.ModuleName}\"" : "null";
        sb.AppendLine(
            "        global::SimpleModule.Database.ModuleModelBuilderExtensions.ApplyHostModuleSchemas("
        );
        sb.AppendLine(
            $"            builder, dbOptions.Value, moduleByEntityType, {identityModuleArg});"
        );

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("HostDbContext.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
