using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class HostDbContextEmitter : IEmitter
{
#pragma warning disable CA1308 // Schema names are conventionally lowercase in PostgreSQL/SQL Server
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.DbContexts.Length == 0)
            return;

        // Abort if any error-level diagnostics were reported (SM0003, SM0005, SM0007)
        var identityCount = 0;
        var hasBadIdentityArgs = false;
        foreach (var ctx in data.DbContexts)
        {
            if (ctx.IsIdentityDbContext)
            {
                identityCount++;
                if (string.IsNullOrEmpty(ctx.IdentityUserTypeFqn))
                    hasBadIdentityArgs = true;
            }
        }

        var hasDuplicateConfigs = false;
        var configEntities = new System.Collections.Generic.HashSet<string>();
        foreach (var config in data.EntityConfigs)
        {
            if (!configEntities.Add(config.EntityFqn))
                hasDuplicateConfigs = true;
        }

        if (identityCount > 1 || hasBadIdentityArgs || hasDuplicateConfigs)
            return;

        // Determine if any module uses IdentityDbContext
        DbContextInfoRecord? identityContext = null;
        foreach (var ctx in data.DbContexts)
        {
            if (ctx.IsIdentityDbContext)
            {
                identityContext = ctx;
                break;
            }
        }

        // Collect all DbSet<T> across modules, deduplicated by entity FQN
        var seenEntities = new System.Collections.Generic.HashSet<string>();
        var allDbSets = new System.Collections.Generic.List<(
            string PropertyName,
            string EntityFqn,
            string ModuleName
        )>();
        foreach (var ctx in data.DbContexts)
        {
            foreach (var dbSet in ctx.DbSets)
            {
                if (seenEntities.Add(dbSet.EntityFqn))
                {
                    allDbSets.Add((dbSet.PropertyName, dbSet.EntityFqn, ctx.ModuleName));
                }
            }
        }

        // Check for duplicate DbSet property names across modules
        var propertyNameOwners = new System.Collections.Generic.Dictionary<
            string,
            (string EntityFqn, string ModuleName)
        >();
        var hasDuplicates = false;
        foreach (var entry in allDbSets)
        {
            if (propertyNameOwners.TryGetValue(entry.PropertyName, out var existing))
            {
                // Same entity type with same property name is fine (deduplicated earlier)
                if (existing.EntityFqn != entry.EntityFqn)
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            DiagnosticEmitter.DuplicateDbSetPropertyName,
                            Location.None,
                            entry.PropertyName,
                            existing.ModuleName,
                            TypeMappingHelpers.StripGlobalPrefix(existing.EntityFqn),
                            entry.ModuleName,
                            TypeMappingHelpers.StripGlobalPrefix(entry.EntityFqn)
                        )
                    );
                    hasDuplicates = true;
                }
            }
            else
            {
                propertyNameOwners[entry.PropertyName] = (entry.EntityFqn, entry.ModuleName);
            }
        }

        if (hasDuplicates)
            return;

        // Build entity-to-module mapping for schema isolation
        var entityToModule = new System.Collections.Generic.Dictionary<string, string>();
        foreach (var entry in allDbSets)
        {
            entityToModule[entry.EntityFqn] = entry.ModuleName;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using SimpleModule.Database;");

        if (identityContext != null)
        {
            sb.AppendLine("using Microsoft.AspNetCore.Identity.EntityFrameworkCore;");
        }

        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Host;");
        sb.AppendLine();

        // Class declaration with primary constructor
        if (identityContext != null)
        {
            sb.AppendLine($"public partial class HostDbContext(");
            sb.AppendLine("    DbContextOptions<HostDbContext> options,");
            sb.AppendLine("    IOptions<DatabaseOptions> dbOptions");
            sb.AppendLine($") : IdentityDbContext<{identityContext.Value.IdentityUserTypeFqn},");
            sb.AppendLine($"                      {identityContext.Value.IdentityRoleTypeFqn},");
            sb.AppendLine(
                $"                      {identityContext.Value.IdentityKeyTypeFqn}>(options)"
            );
        }
        else
        {
            sb.AppendLine("public class HostDbContext(");
            sb.AppendLine("    DbContextOptions<HostDbContext> options,");
            sb.AppendLine("    IOptions<DatabaseOptions> dbOptions");
            sb.AppendLine(") : DbContext(options)");
        }

        sb.AppendLine("{");

        // DbSet properties
        foreach (var dbSet in allDbSets)
        {
            sb.AppendLine($"    public DbSet<{dbSet.EntityFqn}> {dbSet.PropertyName}");
            sb.AppendLine($"        => Set<{dbSet.EntityFqn}>();");
            sb.AppendLine();
        }

        // OnModelCreating
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder builder)");
        sb.AppendLine("    {");

        if (identityContext != null)
        {
            sb.AppendLine("        base.OnModelCreating(builder);");
            sb.AppendLine();
        }

        // Apply IEntityTypeConfiguration<T> implementations
        if (data.EntityConfigs.Length > 0)
        {
            sb.AppendLine(
                "        // Apply IEntityTypeConfiguration<T> found in module assemblies"
            );
            foreach (var config in data.EntityConfigs)
            {
                sb.AppendLine($"        builder.ApplyConfiguration(new {config.ConfigFqn}());");
            }
            sb.AppendLine();
        }

        // Schema isolation (non-SQLite only)
        sb.AppendLine("        // Schema isolation (PostgreSQL/SQL Server only)");
        sb.AppendLine("        var provider = DatabaseProviderDetector.Detect(");
        sb.AppendLine("            dbOptions.Value.DefaultConnection, dbOptions.Value.Provider);");
        sb.AppendLine("        if (provider != DatabaseProvider.Sqlite)");
        sb.AppendLine("        {");

        // Group entities by module for schema assignment
        var moduleNames = new System.Collections.Generic.HashSet<string>();
        foreach (var entry in allDbSets)
        {
            moduleNames.Add(entry.ModuleName);
        }

        foreach (var entry in allDbSets)
        {
            var schema = entry.ModuleName.ToLowerInvariant();
            sb.AppendLine($"            builder.Entity<{entry.EntityFqn}>()");
            sb.AppendLine($"                .Metadata.SetSchema(\"{schema}\");");
        }

        // If there's an IdentityDbContext, assign remaining entities (Identity tables)
        // to that module's schema
        if (identityContext != null)
        {
            var identitySchema = identityContext.Value.ModuleName.ToLowerInvariant();
            sb.AppendLine();
            sb.AppendLine("            // Assign Identity tables to the identity module's schema");
            sb.AppendLine("            foreach (var entityType in builder.Model.GetEntityTypes())");
            sb.AppendLine("            {");
            sb.AppendLine("                if (entityType.GetSchema() is null)");
            sb.AppendLine($"                    entityType.SetSchema(\"{identitySchema}\");");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");

        // SQLite table prefix isolation
        sb.AppendLine("        else");
        sb.AppendLine("        {");

        // For SQLite, apply table prefixes per module
        foreach (var ctx in data.DbContexts)
        {
            var prefix = ctx.ModuleName + "_";
            foreach (var dbSet in ctx.DbSets)
            {
                if (!seenEntities.Contains(dbSet.EntityFqn))
                    continue;
                sb.AppendLine(
                    $"            builder.Entity<{dbSet.EntityFqn}>().ToTable(\"{prefix}\" +"
                );
                sb.AppendLine(
                    $"                (builder.Entity<{dbSet.EntityFqn}>().Metadata.GetTableName() ?? \"{dbSet.PropertyName}\"));"
                );
            }
        }

        // For Identity tables in SQLite, prefix them too
        if (identityContext != null)
        {
            var identityPrefix = identityContext.Value.ModuleName + "_";
            sb.AppendLine();
            sb.AppendLine("            // Prefix Identity tables for SQLite");
            sb.AppendLine("            foreach (var entityType in builder.Model.GetEntityTypes())");
            sb.AppendLine("            {");
            sb.AppendLine("                var tableName = entityType.GetTableName();");
            sb.AppendLine(
                $"                if (tableName is not null && !tableName.StartsWith(\"{identityPrefix}\", global::System.StringComparison.Ordinal))"
            );

            // Check it's not already prefixed by another module
            sb.AppendLine("                {");
            sb.AppendLine("                    var alreadyPrefixed = false;");
            foreach (var ctx2 in data.DbContexts)
            {
                if (ctx2.FullyQualifiedName == identityContext.Value.FullyQualifiedName)
                    continue;
                sb.AppendLine(
                    $"                    if (tableName.StartsWith(\"{ctx2.ModuleName}_\", global::System.StringComparison.Ordinal)) alreadyPrefixed = true;"
                );
            }
            sb.AppendLine(
                $"                    if (!alreadyPrefixed) entityType.SetTableName(\"{identityPrefix}\" + tableName);"
            );
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("HostDbContext.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
#pragma warning restore CA1308
}
