using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class JsonResolverEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.DtoTypes.Length == 0)
            return;

        var dtoTypes = data.DtoTypes;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable IL2026");
        sb.AppendLine("#pragma warning disable IL3050");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public sealed class ModulesJsonResolver : IJsonTypeInfoResolver");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly ModulesJsonResolver Instance = new();");
        sb.AppendLine();
        sb.AppendLine(
            "    public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)"
        );
        sb.AppendLine("    {");

        foreach (var dto in dtoTypes)
        {
            sb.AppendLine($"        if (type == typeof({dto.FullyQualifiedName}))");
            sb.AppendLine($"            return Create_{dto.SafeName}(options);");
        }

        sb.AppendLine("        return null;");
        sb.AppendLine("    }");

        foreach (var dto in dtoTypes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    private static JsonTypeInfo Create_{dto.SafeName}(JsonSerializerOptions options)"
            );
            sb.AppendLine("    {");
            sb.AppendLine(
                $"        var info = JsonTypeInfo.CreateJsonTypeInfo<{dto.FullyQualifiedName}>(options);"
            );
            sb.AppendLine(
                $"        info.CreateObject = static () => new {dto.FullyQualifiedName}();"
            );

            foreach (var prop in dto.Properties)
            {
                var jsonName = char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);
                sb.AppendLine(
                    $"        var prop_{prop.Name} = info.CreateJsonPropertyInfo(typeof({prop.TypeFqn}), \"{jsonName}\");"
                );
                sb.AppendLine(
                    $"        prop_{prop.Name}.Get = static obj => (({dto.FullyQualifiedName})obj).{prop.Name};"
                );

                if (prop.HasSetter)
                {
                    sb.AppendLine(
                        $"        prop_{prop.Name}.Set = static (obj, val) => (({dto.FullyQualifiedName})obj).{prop.Name} = ({prop.TypeFqn})val!;"
                    );
                }

                sb.AppendLine($"        info.Properties.Add(prop_{prop.Name});");
            }

            sb.AppendLine("        return info;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        context.AddSource(
            "ModulesJsonResolver.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
