using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class LocalizationExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (!data.Modules.Any(m => m.ModuleName == "Localization"))
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Hosting;");
        sb.AppendLine();
        sb.AppendLine("public static class LocalizationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void InitializeLocalization(this IHost host)");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        var loader = host.Services.GetRequiredService<global::SimpleModule.Localization.Services.TranslationLoader>();"
        );
        sb.AppendLine("        var assemblies = new System.Reflection.Assembly[]");
        sb.AppendLine("        {");

        foreach (var module in data.Modules)
        {
            sb.AppendLine(
                $"            typeof({module.FullyQualifiedName}).Assembly,"
            );
        }

        sb.AppendLine("        };");
        sb.AppendLine("        loader.Initialize(assemblies);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("LocalizationExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
