using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class MenuExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = data.Modules;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Core.Menu;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class MenuExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static IServiceCollection CollectModuleMenuItems(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        var menus = new MenuBuilder();");

        foreach (var module in modules.Where(m => m.HasConfigureMenu))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine($"        ModuleExtensions.{fieldName}.ConfigureMenu(menus);");
        }

        sb.AppendLine(
            "        services.AddSingleton<IMenuRegistry>(new MenuRegistry(menus.ToList()));"
        );
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("MenuExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
