using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

/// <summary>
/// Emits extension methods on SimpleModuleOptions for each discovered IModuleOptions class
/// (e.g., ConfigureProducts()) and a RegisterModuleOptionsDefaults() helper that registers
/// IOptions&lt;T&gt; for all discovered options types.
/// </summary>
internal sealed class ModuleOptionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var optionsByModule = ModuleOptionsRecord.GroupByModule(data.ModuleOptions);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated extension methods for configuring module options.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ModuleOptionsExtensions");
        sb.AppendLine("{");

        // Generate a Configure{ModuleName}() extension method for each unique module options class
        foreach (var kvp in optionsByModule)
        {
            // Only emit for the first options class per module (diagnostic catches duplicates)
            var opt = kvp.Value[0];
            var moduleName = opt.ModuleName;

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Configures options for the {moduleName} module.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine(
                $"    public static SimpleModuleOptions Configure{moduleName}(this SimpleModuleOptions options, System.Action<{opt.FullyQualifiedName}> configure)"
            );
            sb.AppendLine("    {");
            sb.AppendLine("        return options.ConfigureModule(configure);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Generate RegisterModuleOptionsDefaults method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine(
            "    /// Registers IOptions&lt;T&gt; defaults for all discovered module options."
        );
        sb.AppendLine("    /// </summary>");
        sb.AppendLine(
            "    internal static void RegisterModuleOptionsDefaults(IServiceCollection services)"
        );
        sb.AppendLine("    {");

        foreach (var kvp in optionsByModule)
        {
            var opt = kvp.Value[0];
            sb.AppendLine($"        services.AddOptions<{opt.FullyQualifiedName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "ModuleOptionsExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
