using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

/// <summary>
/// Emits the module manifest as an assembly-level
/// <c>[assembly: ModuleManifest("{json}")]</c> attribute into module-kind
/// compilations (projects built with <c>SimpleModuleProjectKind=Module</c>).
/// Source generators cannot add embedded resources, so the attribute is the
/// closest in-assembly equivalent — readable at runtime via reflection and by
/// tooling via System.Reflection.Metadata without loading the assembly.
/// </summary>
internal static class ModuleManifestEmitter
{
    internal const int SchemaVersion = 1;

    internal static void Emit(
        SourceProductionContext context,
        DiscoveryData data,
        string frameworkCompatOverride
    )
    {
        // Only the module declared in THIS compilation gets a manifest; modules
        // visible through references belong to other assemblies. The attribute
        // allows one manifest per assembly, so a multi-module assembly (not a
        // supported packaging shape) gets a manifest for its first module.
        var module = data.Modules.FirstOrDefault(m => m.AssemblyName == data.HostAssemblyName);
        if (module.ModuleName is null or "")
            return;

        var json = BuildManifestJson(module, data, frameworkCompatOverride);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine(
            $"[assembly: global::SimpleModule.Core.Modules.ModuleManifest({ToCSharpLiteral(json)})]"
        );

        context.AddSource("ModuleManifest.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string BuildManifestJson(
        ModuleInfoRecord module,
        DiscoveryData data,
        string frameworkCompatOverride
    )
    {
        var permissions = data
            .PermissionClasses.Where(p => p.ModuleName == module.ModuleName)
            .SelectMany(p => p.Fields)
            .Where(f => f.IsConstString && !string.IsNullOrEmpty(f.Value))
            .Select(f => f.Value)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(v => v, StringComparer.Ordinal)
            .ToList();

        var pages = module
            .Views.Select(v => v.Page)
            .Where(p => !string.IsNullOrEmpty(p))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(p => p, StringComparer.Ordinal)
            .ToList();

        var eventsPublished = data
            .EventTypes.Where(e => e.ModuleName == module.ModuleName)
            .Select(e => StripGlobal(e.FullyQualifiedName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();

        var eventsConsumed = data
            .EventHandlers.Where(h => h.ModuleName == module.ModuleName)
            .Select(h => StripGlobal(h.EventFullyQualifiedName))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();

        var hasDbContext = data.DbContexts.Any(c => c.ModuleName == module.ModuleName);

        var frontendEntry =
            module.Views.Length > 0
                ? $"_content/{module.AssemblyName}/{module.AssemblyName}.pages.js"
                : null;

        var displayName = string.IsNullOrEmpty(module.DisplayName)
            ? module.ModuleName
            : module.DisplayName;

        var frameworkCompat = !string.IsNullOrEmpty(frameworkCompatOverride)
            ? frameworkCompatOverride
            : DefaultFrameworkCompat(data.CoreAssemblyVersion);

        var sb = new StringBuilder();
        sb.Append('{');
        AppendProperty(sb, "schemaVersion", SchemaVersion);
        AppendProperty(sb, "id", module.AssemblyName);
        AppendProperty(sb, "name", module.ModuleName);
        AppendProperty(sb, "displayName", displayName);
        AppendProperty(sb, "version", module.Version);
        AppendProperty(sb, "frameworkCompat", frameworkCompat);
        AppendProperty(sb, "routePrefix", module.RoutePrefix);
        AppendProperty(sb, "viewPrefix", module.ViewPrefix);
        AppendProperty(sb, "schema", module.ModuleName);
        AppendArrayProperty(sb, "permissions", permissions);
        if (frontendEntry is null)
        {
            sb.Append("\"frontendEntry\":null,");
        }
        else
        {
            AppendProperty(sb, "frontendEntry", frontendEntry);
        }
        AppendArrayProperty(sb, "pages", pages);
        AppendArrayProperty(sb, "eventsPublished", eventsPublished);
        AppendArrayProperty(sb, "eventsConsumed", eventsConsumed);
        sb.Append("\"hasDbContext\":").Append(hasDbContext ? "true" : "false");
        sb.Append('}');
        return sb.ToString();
    }

    private static string DefaultFrameworkCompat(string coreVersion)
    {
        if (string.IsNullOrEmpty(coreVersion))
            return "";

        // The assembly identity carries no prerelease tag, so the referenced Core
        // may actually be a prerelease of this version. "-0" is SemVer's smallest
        // prerelease: the bound admits prereleases of coreVersion itself, encoding
        // that semantic in the manifest rather than in each consumer.
        var majorPart = coreVersion.Split('.')[0];
        return int.TryParse(majorPart, out var major)
            ? $">={coreVersion}-0 <{major + 1}.0.0"
            : $">={coreVersion}-0";
    }

    private static string StripGlobal(string fullyQualifiedName) =>
        fullyQualifiedName.StartsWith("global::", StringComparison.Ordinal)
            ? fullyQualifiedName.Substring("global::".Length)
            : fullyQualifiedName;

    private static void AppendProperty(StringBuilder sb, string name, int value) =>
        sb.Append('"').Append(name).Append("\":").Append(value).Append(',');

    private static void AppendProperty(StringBuilder sb, string name, string value) =>
        sb.Append('"').Append(name).Append("\":").Append(JsonString(value)).Append(',');

    private static void AppendArrayProperty(StringBuilder sb, string name, List<string> values)
    {
        sb.Append('"').Append(name).Append("\":[");
        for (var i = 0; i < values.Count; i++)
        {
            if (i > 0)
                sb.Append(',');
            sb.Append(JsonString(values[i]));
        }
        sb.Append("],");
    }

    private static string JsonString(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (c < 0x20)
                    {
                        sb.Append("\\u")
                            .Append(
                                ((int)c).ToString(
                                    "x4",
                                    System.Globalization.CultureInfo.InvariantCulture
                                )
                            );
                    }
                    else
                    {
                        sb.Append(c);
                    }
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    /// <summary>
    /// Renders the JSON as a verbatim C# string literal for the attribute argument.
    /// </summary>
    private static string ToCSharpLiteral(string json) => "@\"" + json.Replace("\"", "\"\"") + "\"";
}
