using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class ModuleExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = data.Modules;
        var hasDtoTypes = data.DtoTypes.Length > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable IL2026");
        sb.AppendLine("#pragma warning disable IL3050");
        sb.AppendLine("using Microsoft.AspNetCore.Http.Json;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using SimpleModule.Core.Authorization;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class ModuleExtensions");
        sb.AppendLine("{");

        // Generate shared module instances
        foreach (var module in modules)
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine(
                $"    internal static readonly {module.FullyQualifiedName} {fieldName} = new();"
            );
        }

        sb.AppendLine();
        sb.AppendLine(
            "    public static IServiceCollection AddModules(this IServiceCollection services, IConfiguration configuration)"
        );
        sb.AppendLine("    {");

        foreach (var module in modules.Where(m => m.HasConfigureServices))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine($"        {fieldName}.ConfigureServices(services, configuration);");
        }

        sb.AppendLine();
        sb.AppendLine("        var permissionBuilder = new PermissionRegistryBuilder();");

        foreach (var module in modules.Where(m => m.HasConfigurePermissions))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine($"        {fieldName}.ConfigurePermissions(permissionBuilder);");
        }

        sb.AppendLine("        var permissionRegistry = permissionBuilder.Build();");
        sb.AppendLine("        services.AddSingleton(permissionRegistry);");
        sb.AppendLine();
        sb.AppendLine("        services.AddAuthorizationBuilder()");
        sb.AppendLine("            .SetDefaultPolicy(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build());");
        sb.AppendLine("        services.AddSingleton<IAuthorizationHandler, PermissionAuthorizationHandler>();");

        if (hasDtoTypes)
        {
            sb.AppendLine();
            sb.AppendLine("        services.ConfigureHttpJsonOptions(options =>");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            options.SerializerOptions.TypeInfoResolver = System.Text.Json.Serialization.Metadata.JsonTypeInfoResolver.Combine("
            );
            sb.AppendLine("                ModulesJsonResolver.Instance,");
            sb.AppendLine(
                "                new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver());"
            );
            sb.AppendLine("        });");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ModuleExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
