using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class ModuleExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var (sortedModules, sortResult) = TopologicalSort.SortModulesWithResult(data);
        var hasDtoTypes = data.DtoTypes.Length > 0;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable IL2026");
        sb.AppendLine("#pragma warning disable IL3050");
        sb.AppendLine("using Microsoft.AspNetCore.Http.Json;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using SimpleModule.Core.Authorization;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class ModuleExtensions");
        sb.AppendLine("{");

        // Generate shared module instances
        foreach (var module in sortedModules)
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine(
                $"    internal static readonly {module.FullyQualifiedName} {fieldName} = new();"
            );
        }

        sb.AppendLine();
        sb.AppendLine(
            "    public static IServiceCollection AddModules(this IServiceCollection services, IConfiguration configuration)"
        );
        sb.AppendLine("    {");

        var currentPhase = -1;
        foreach (var module in sortedModules.Where(m => m.HasConfigureServices))
        {
            if (
                sortResult.IsSuccess
                && sortResult.Phases.TryGetValue(module.ModuleName, out var phase)
            )
            {
                if (phase != currentPhase)
                {
                    currentPhase = phase;
                    sb.AppendLine();
                    if (
                        sortResult.DependenciesOf.TryGetValue(module.ModuleName, out var deps)
                        && deps.Length > 0
                    )
                    {
                        sb.AppendLine(
                            $"        // Phase {phase + 1}: Depends on {string.Join(", ", deps)}"
                        );
                    }
                    else
                    {
                        sb.AppendLine($"        // Phase {phase + 1}: No dependencies");
                    }
                }
            }
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine(
                $"        ((global::SimpleModule.Core.IModule){fieldName}).ConfigureServices(services, configuration);"
            );
        }

        sb.AppendLine();
        sb.AppendLine("        // Auto-discovered contract implementations");

        // Group by interface FQN and only emit if exactly one valid implementation
        var implsByInterface = new Dictionary<string, List<ContractImplementationRecord>>();
        foreach (var impl in data.ContractImplementations)
        {
            if (!impl.IsPublic || impl.IsAbstract)
                continue;

            if (!implsByInterface.TryGetValue(impl.InterfaceFqn, out var list))
            {
                list = new List<ContractImplementationRecord>();
                implsByInterface[impl.InterfaceFqn] = list;
            }
            list.Add(impl);
        }

        foreach (var kvp in implsByInterface)
        {
            if (kvp.Value.Count == 1)
            {
                var impl = kvp.Value[0];
                sb.AppendLine(
                    $"        services.AddScoped<{impl.InterfaceFqn}, {impl.ImplementationFqn}>();"
                );
            }
        }

        sb.AppendLine();
        sb.AppendLine("        var permissionBuilder = new PermissionRegistryBuilder();");

        foreach (var module in sortedModules.Where(m => m.HasConfigurePermissions))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine(
                $"        ((global::SimpleModule.Core.IModule){fieldName}).ConfigurePermissions(permissionBuilder);"
            );
        }

        sb.AppendLine();
        sb.AppendLine("        // Auto-discovered permission classes (IModulePermissions)");
        foreach (var perm in data.PermissionClasses)
        {
            if (perm.IsSealed)
            {
                sb.AppendLine(
                    $"        permissionBuilder.AddPermissions<{perm.FullyQualifiedName}>();"
                );
            }
        }

        sb.AppendLine("        var permissionRegistry = permissionBuilder.Build();");
        sb.AppendLine("        services.AddSingleton(permissionRegistry);");
        sb.AppendLine();
        sb.AppendLine("        services.AddAuthorizationBuilder()");
        sb.AppendLine(
            "            .SetDefaultPolicy(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build());"
        );
        sb.AppendLine(
            "        services.AddSingleton<IAuthorizationHandler, PermissionAuthorizationHandler>();"
        );

        if (hasDtoTypes)
        {
            sb.AppendLine();
            sb.AppendLine("        services.ConfigureHttpJsonOptions(options =>");
            sb.AppendLine("        {");
            sb.AppendLine(
                "            options.SerializerOptions.TypeInfoResolver = System.Text.Json.Serialization.Metadata.JsonTypeInfoResolver.Combine("
            );
            sb.AppendLine("                ModulesJsonResolver.Instance,");
            sb.AppendLine(
                "                new System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver());"
            );
            sb.AppendLine("        });");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ModuleExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
