using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class PageRegistryEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using SimpleModule.Core.Menu;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class PageRegistry");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static IReadOnlyList<AvailablePage> Pages { get; } = new AvailablePage[]"
        );
        sb.AppendLine("    {");

        foreach (var module in data.Modules)
        {
            if (module.Views.Length == 0)
                continue;

            for (var i = 0; i < module.Views.Length; i++)
            {
                var view = module.Views[i];
                sb.AppendLine(
                    string.Format(
                        System.Globalization.CultureInfo.InvariantCulture,
                        "        new AvailablePage(\"{0}\", \"{1}\", \"{2}\"),",
                        view.Page,
                        module.ViewPrefix,
                        module.ModuleName
                    )
                );
            }
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("PageRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
