using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class RazorComponentExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = data.Modules;
        var razorModules = modules.Where(m => m.HasRazorComponents).ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class RazorComponentExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static RazorComponentsEndpointConventionBuilder AddModuleAssemblies("
        );
        sb.AppendLine("        this RazorComponentsEndpointConventionBuilder builder)");
        sb.AppendLine("    {");

        if (razorModules.Count > 0)
        {
            sb.AppendLine("        builder.AddAdditionalAssemblies(");
            for (var i = 0; i < razorModules.Count; i++)
            {
                var suffix = i < razorModules.Count - 1 ? "," : ");";
                sb.AppendLine(
                    $"            typeof({razorModules[i].FullyQualifiedName}).Assembly{suffix}"
                );
            }
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "RazorComponentExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
