using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class RoutesEmitter : IEmitter
{
    private static readonly Regex RouteParamRegex = new Regex(
        @"\{[*?]*(\w+?)(?:[:?*].*?)?\}",
        RegexOptions.Compiled
    );

    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = TopologicalSort.SortModules(data);

        // Only emit if at least one endpoint has a route template
        if (!modules.Any(m => HasAnyRouteTemplates(m)))
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class ModuleRoutes");
        sb.AppendLine("{");

        foreach (var module in modules)
        {
            if (!HasAnyRouteTemplates(module))
                continue;

            sb.AppendLine($"    public static class {module.ModuleName}");
            sb.AppendLine("    {");

            if (!string.IsNullOrEmpty(module.RoutePrefix))
                sb.AppendLine($"        public const string ApiPrefix = \"{module.RoutePrefix}\";");

            if (!string.IsNullOrEmpty(module.ViewPrefix))
                sb.AppendLine($"        public const string ViewPrefix = \"{module.ViewPrefix}\";");

            // API endpoints
            var apiEndpoints = module.Endpoints.Where(e => e.RouteTemplate.Length > 0).ToList();
            if (apiEndpoints.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        public static class Api");
                sb.AppendLine("        {");

                foreach (var endpoint in apiEndpoints)
                {
                    EmitRouteMethod(
                        sb,
                        endpoint.FullyQualifiedName,
                        module.RoutePrefix,
                        endpoint.RouteTemplate,
                        "            "
                    );
                }

                sb.AppendLine("        }");
            }

            // View endpoints
            var viewEndpoints = module.Views.Where(v => v.RouteTemplate.Length > 0).ToList();
            if (viewEndpoints.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("        public static class Views");
                sb.AppendLine("        {");

                foreach (var view in viewEndpoints)
                {
                    EmitRouteMethod(
                        sb,
                        view.FullyQualifiedName,
                        module.ViewPrefix,
                        view.RouteTemplate,
                        "            "
                    );
                }

                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource("ModuleRoutes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    internal static bool HasAnyRouteTemplates(ModuleInfoRecord module)
    {
        return module.Endpoints.Any(e => e.RouteTemplate.Length > 0)
            || module.Views.Any(v => v.RouteTemplate.Length > 0);
    }

    private static void EmitRouteMethod(
        StringBuilder sb,
        string fullyQualifiedName,
        string prefix,
        string routeTemplate,
        string indent
    )
    {
        var methodName = DeriveMethodName(fullyQualifiedName);
        var fullRoute = CombineRoute(prefix, routeTemplate);
        var parameters = ExtractRouteParameters(routeTemplate);

        if (parameters.Count == 0)
        {
            var cleanRoute = StripRouteConstraints(fullRoute);
            sb.AppendLine($"{indent}public static string {methodName}() => \"{cleanRoute}\";");
        }
        else
        {
            var paramList = string.Join(", ", parameters.Select(p => $"object {p}"));
            var interpolated = BuildInterpolatedRoute(prefix, routeTemplate);
            sb.AppendLine(
                $"{indent}public static string {methodName}({paramList}) => $\"{interpolated}\";"
            );
        }
    }

    internal static string DeriveMethodName(string fullyQualifiedName)
    {
        var name = TypeMappingHelpers.StripGlobalPrefix(fullyQualifiedName);
        // Take the last segment (class name)
        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
            name = name.Substring(lastDot + 1);

        // Strip common suffixes
        if (name.EndsWith("Endpoint", StringComparison.Ordinal))
            name = name.Substring(0, name.Length - "Endpoint".Length);
        else if (name.EndsWith("View", StringComparison.Ordinal))
            name = name.Substring(0, name.Length - "View".Length);

        return name;
    }

    internal static string CombineRoute(string prefix, string template)
    {
        if (string.IsNullOrEmpty(prefix))
            return template;
        if (template == "/")
            return prefix;

        // Ensure no double slashes
        var p = prefix.TrimEnd('/');
        var t = template.StartsWith("/", StringComparison.Ordinal) ? template : "/" + template;
        return p + t;
    }

    internal static List<string> ExtractRouteParameters(string routeTemplate)
    {
        var result = new List<string>();
        foreach (Match match in RouteParamRegex.Matches(routeTemplate))
        {
            result.Add(match.Groups[1].Value);
        }
        return result;
    }

    /// <summary>
    /// Strips ASP.NET route constraints from a route template.
    /// E.g., "/{id:guid}" → "/{id}", "/{id:int}" → "/{id}", "/{**key}" → "/{key}"
    /// </summary>
    internal static string StripRouteConstraints(string route)
    {
        return RouteParamRegex.Replace(route, "{$1}");
    }

    private static string BuildInterpolatedRoute(string prefix, string routeTemplate)
    {
        return StripRouteConstraints(CombineRoute(prefix, routeTemplate));
    }
}
