using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class SettingsExtensionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = TopologicalSort.SortModules(data);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using SimpleModule.Core.Settings;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Core;");
        sb.AppendLine();
        sb.AppendLine("public static class SettingsExtensions");
        sb.AppendLine("{");
        sb.AppendLine(
            "    public static IServiceCollection CollectModuleSettings(this IServiceCollection services)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        var settings = new SettingsBuilder();");

        foreach (var module in modules.Where(m => m.HasConfigureSettings))
        {
            var fieldName = TypeMappingHelpers.GetModuleFieldName(module.FullyQualifiedName);
            sb.AppendLine($"        ((global::SimpleModule.Core.IModule)ModuleExtensions.{fieldName}).ConfigureSettings(settings);");
        }

        sb.AppendLine(
            "        services.AddSingleton<ISettingsDefinitionRegistry>(new SettingsDefinitionRegistry(settings.ToList()));"
        );
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("SettingsExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
