using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class TypeScriptRoutesEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = TopologicalSort.SortModules(data);

        // Only emit if at least one endpoint has a route template
        if (!modules.Any(m => RoutesEmitter.HasAnyRouteTemplates(m)))
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#if SIMPLEMODULE_TS");
        sb.AppendLine("/*");
        sb.AppendLine("// @routes");
        sb.AppendLine();
        sb.AppendLine("export const routes = {");

        foreach (var module in modules)
        {
            if (!RoutesEmitter.HasAnyRouteTemplates(module))
                continue;

            var moduleCamel = ToCamelCase(module.ModuleName);
            sb.AppendLine($"  {moduleCamel}: {{");

            // API endpoints
            var apiEndpoints = module.Endpoints.Where(e => e.RouteTemplate.Length > 0).ToList();
            if (apiEndpoints.Count > 0)
            {
                sb.AppendLine("    api: {");
                foreach (var ep in apiEndpoints)
                {
                    EmitTsRouteEntry(
                        sb,
                        ep.FullyQualifiedName,
                        module.RoutePrefix,
                        ep.RouteTemplate,
                        "      "
                    );
                }
                sb.AppendLine("    },");
            }

            // View endpoints
            var viewEndpoints = module.Views.Where(v => v.RouteTemplate.Length > 0).ToList();
            if (viewEndpoints.Count > 0)
            {
                sb.AppendLine("    views: {");
                foreach (var view in viewEndpoints)
                {
                    EmitTsRouteEntry(
                        sb,
                        view.FullyQualifiedName,
                        module.ViewPrefix,
                        view.RouteTemplate,
                        "      "
                    );
                }
                sb.AppendLine("    },");
            }

            sb.AppendLine("  },");
        }

        sb.AppendLine("} as const;");
        sb.AppendLine();
        sb.AppendLine("*/");
        sb.AppendLine("#endif");

        context.AddSource("TypeScriptRoutes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitTsRouteEntry(
        StringBuilder sb,
        string fullyQualifiedName,
        string prefix,
        string routeTemplate,
        string indent
    )
    {
        var methodName = ToCamelCase(RoutesEmitter.DeriveMethodName(fullyQualifiedName));
        var parameters = RoutesEmitter.ExtractRouteParameters(routeTemplate);
        var fullRoute = RoutesEmitter.StripRouteConstraints(
            RoutesEmitter.CombineRoute(prefix, routeTemplate)
        );

        if (parameters.Count == 0)
        {
            sb.AppendLine($"{indent}{methodName}: () => '{fullRoute}' as const,");
        }
        else
        {
            var paramList = string.Join(", ", parameters.Select(p => $"{p}: string | number"));
            var templateLiteral = fullRoute;
            foreach (var param in parameters)
            {
                templateLiteral = templateLiteral.Replace("{" + param + "}", "${" + param + "}");
            }

            sb.AppendLine($"{indent}{methodName}: ({paramList}) => `{templateLiteral}`,");
        }
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
