using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class TypeScriptRoutesEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        var modules = TopologicalSort.SortModules(data);

        // Only emit if at least one endpoint has a route template
        if (!modules.Any(m => HasAnyRouteTemplates(m)))
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#if SIMPLEMODULE_TS");
        sb.AppendLine("/*");
        sb.AppendLine("// @routes");
        sb.AppendLine();
        sb.AppendLine("export const routes = {");

        var moduleIndex = 0;
        foreach (var module in modules)
        {
            if (!HasAnyRouteTemplates(module))
                continue;

            var moduleCamel = ToCamelCase(module.ModuleName);
            sb.AppendLine($"  {moduleCamel}: {{");

            // API endpoints
            var apiEndpoints = module.Endpoints.Where(e => e.RouteTemplate.Length > 0).ToList();
            if (apiEndpoints.Count > 0)
            {
                sb.AppendLine("    api: {");
                for (var i = 0; i < apiEndpoints.Count; i++)
                {
                    var ep = apiEndpoints[i];
                    var comma = ",";
                    EmitTsRouteEntry(
                        sb,
                        ep.FullyQualifiedName,
                        module.RoutePrefix,
                        ep.RouteTemplate,
                        "      ",
                        comma
                    );
                }
                sb.AppendLine("    },");
            }

            // View endpoints
            var viewEndpoints = module.Views.Where(v => v.RouteTemplate.Length > 0).ToList();
            if (viewEndpoints.Count > 0)
            {
                sb.AppendLine("    views: {");
                for (var i = 0; i < viewEndpoints.Count; i++)
                {
                    var view = viewEndpoints[i];
                    var comma = ",";
                    EmitTsRouteEntry(
                        sb,
                        view.FullyQualifiedName,
                        module.ViewPrefix,
                        view.RouteTemplate,
                        "      ",
                        comma
                    );
                }
                sb.AppendLine("    },");
            }

            sb.AppendLine("  },");
            moduleIndex++;
        }

        sb.AppendLine("} as const;");
        sb.AppendLine();
        sb.AppendLine("*/");
        sb.AppendLine("#endif");

        context.AddSource("TypeScriptRoutes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool HasAnyRouteTemplates(ModuleInfoRecord module)
    {
        return module.Endpoints.Any(e => e.RouteTemplate.Length > 0)
            || module.Views.Any(v => v.RouteTemplate.Length > 0);
    }

    private static void EmitTsRouteEntry(
        StringBuilder sb,
        string fullyQualifiedName,
        string prefix,
        string routeTemplate,
        string indent,
        string comma
    )
    {
        var methodName = ToCamelCase(RoutesEmitter.DeriveMethodName(fullyQualifiedName));
        var parameters = RoutesEmitter.ExtractRouteParameters(routeTemplate);

        if (parameters.Count == 0)
        {
            var fullRoute = RoutesEmitter.CombineRoute(prefix, routeTemplate);
            sb.AppendLine($"{indent}{methodName}: () => '{fullRoute}' as const{comma}");
        }
        else
        {
            var paramList = string.Join(", ", parameters.Select(p => $"{p}: string | number"));
            var fullRoute = RoutesEmitter.CombineRoute(prefix, routeTemplate);

            // Strip route constraints and convert to TS template literal: {id:guid} → ${id}
            var templateLiteral = RoutesEmitter.StripRouteConstraints(fullRoute);
            foreach (var param in parameters)
            {
                templateLiteral = templateLiteral.Replace("{" + param + "}", "${" + param + "}");
            }

            sb.AppendLine($"{indent}{methodName}: ({paramList}) => `{templateLiteral}`{comma}");
        }
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
