using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class TypeScriptDefinitionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.DtoTypes.Length == 0)
            return;

        var dtoTypes = data.DtoTypes;

        // Build a set of known DTO FQNs so nested references resolve to their TS interface name
        var knownDtoTypes = new System.Collections.Generic.Dictionary<string, string>();
        foreach (var dto in dtoTypes)
        {
            var typeName = dto.FullyQualifiedName;
            var shortName = typeName.Contains(".")
                ? typeName.Substring(typeName.LastIndexOf('.') + 1)
                : typeName;
            shortName = shortName.Replace("global::", "");
            knownDtoTypes[dto.FullyQualifiedName] = shortName;
        }

        // Group DTOs by module name (first namespace segment, e.g. "Products" from "global::Products.Contracts.Product")
        var moduleGroups = new System.Collections.Generic.Dictionary<
            string,
            System.Collections.Generic.List<DtoTypeInfoRecord>
        >();
        foreach (var dto in dtoTypes)
        {
            var moduleName = TypeMappingHelpers.GetModuleNameFromFqn(dto.FullyQualifiedName);
            if (!moduleGroups.TryGetValue(moduleName, out var list))
            {
                list = new System.Collections.Generic.List<DtoTypeInfoRecord>();
                moduleGroups[moduleName] = list;
            }
            list.Add(dto);
        }

        // Emit one file per module
        foreach (var kvp in moduleGroups)
        {
            var moduleName = kvp.Key;
            var moduleDtos = kvp.Value;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#if SIMPLEMODULE_TS");
            sb.AppendLine("/*");
            sb.AppendLine($"// @module {moduleName}");
            sb.AppendLine();

            foreach (var dto in moduleDtos)
            {
                var shortName = knownDtoTypes[dto.FullyQualifiedName];
                sb.AppendLine($"export interface {shortName} {{");
                foreach (var prop in dto.Properties)
                {
                    var tsType = TypeMappingHelpers.MapCSharpTypeToTypeScript(prop.TypeFqn, knownDtoTypes);
                    var camelName = char.ToLowerInvariant(prop.Name[0]) + prop.Name.Substring(1);
                    sb.AppendLine($"  {camelName}: {tsType};");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }

            sb.AppendLine("*/");
            sb.AppendLine("#endif");

            context.AddSource(
                $"DtoTypeScript_{moduleName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
    }
}
