using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class ValueConverterConventionsEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        if (data.VogenValueObjects.Length == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace SimpleModule.Host;");
        sb.AppendLine();
        sb.AppendLine("public partial class HostDbContext");
        sb.AppendLine("{");
        sb.AppendLine(
            "    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)"
        );
        sb.AppendLine("    {");

        foreach (var vo in data.VogenValueObjects)
        {
            sb.AppendLine($"        configurationBuilder.Properties<{vo.TypeFqn}>()");
            sb.AppendLine(
                $"            .HaveConversion<{vo.ConverterFqn}, {vo.ComparerFqn}>();"
            );
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "HostDbContext.Conventions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8)
        );
    }
}
