using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class ViewPagesEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        foreach (var module in data.Modules)
        {
            if (module.Views.Length == 0)
                continue;

            // Derive the hint name from the module's full FQN so two module classes
            // with the same simple name in different namespaces never collide in AddSource.
            var fqn = TypeMappingHelpers.StripGlobalPrefix(module.FullyQualifiedName);
            var hintName = fqn.Replace('.', '_').Replace('+', '_');

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#if SIMPLEMODULE_TS");
            sb.AppendLine("/*");

            // Generate lazy import entries for code splitting
            sb.AppendLine("export const pages: Record<string, any> = {");

            for (var i = 0; i < module.Views.Length; i++)
            {
                var view = module.Views[i];
                var componentName = view.Page.Contains("/")
                    ? view.Page.Substring(view.Page.LastIndexOf('/') + 1)
                    : view.Page;
                var comma = i < module.Views.Length - 1 ? "," : "";
                sb.AppendLine($"  '{view.Page}': () => import('./{componentName}'){comma}");
            }

            sb.AppendLine("};");
            sb.AppendLine("*/");
            sb.AppendLine("#endif");

            context.AddSource(
                $"ViewPages_{hintName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
    }
}
