using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SimpleModule.Generator;

internal sealed class ViewPagesEmitter : IEmitter
{
    public void Emit(SourceProductionContext context, DiscoveryData data)
    {
        foreach (var module in data.Modules)
        {
            if (module.Views.Length == 0)
                continue;

            // Extract module name from FQN (e.g., "global::SimpleModule.Products.ProductsModule" -> "Products")
            var fqn = TypeMappingHelpers.StripGlobalPrefix(module.FullyQualifiedName);
            var moduleName = fqn.Contains(".") ? fqn.Substring(fqn.LastIndexOf('.') + 1) : fqn;
            if (moduleName.EndsWith("Module", StringComparison.Ordinal))
                moduleName = moduleName.Substring(0, moduleName.Length - "Module".Length);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#if SIMPLEMODULE_TS");
            sb.AppendLine("/*");

            // Generate lazy import entries for code splitting
            sb.AppendLine("export const pages: Record<string, any> = {");

            for (var i = 0; i < module.Views.Length; i++)
            {
                var view = module.Views[i];
                var componentName = view.Page.Contains("/")
                    ? view.Page.Substring(view.Page.LastIndexOf('/') + 1)
                    : view.Page;
                var comma = i < module.Views.Length - 1 ? "," : "";
                sb.AppendLine($"  '{view.Page}': () => import('../Views/{componentName}'){comma}");
            }

            sb.AppendLine("};");
            sb.AppendLine("*/");
            sb.AppendLine("#endif");

            context.AddSource(
                $"ViewPages_{moduleName}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
    }
}
