using SimpleModule.Core.Events;

namespace SimpleModule.Users.Contracts.Events;

/// <summary>
/// Raised after the user's security stamp has been regenerated by the "Sign out everywhere"
/// action. Subscribers may take additional revocation actions — e.g., OpenIddict revokes any
/// outstanding access/refresh tokens, since bearer holders bypass the cookie-side
/// SecurityStampValidator.
/// </summary>
public sealed record UserSignedOutEverywhereEvent(UserId UserId) : IEvent;
