import { sleep } from 'k6';
import http from 'k6/http';
import { type AuthResult, authenticate, authHeaders } from '../lib/auth.ts';
import { config, defaultThresholds, loadProfiles, tlsOptions } from '../lib/config.ts';
import { checkResponse, randomString } from '../lib/helpers.ts';

const profile = __ENV.K6_PROFILE || 'smoke';

export const options = {
  ...tlsOptions,
  stages: loadProfiles[profile]?.stages || loadProfiles.smoke.stages,
  thresholds: {
    ...defaultThresholds,
    'http_req_duration{name:list-pages}': ['p(95)<500'],
    'http_req_duration{name:create-page}': ['p(95)<800'],
    'http_req_duration{name:get-page}': ['p(95)<500'],
    'http_req_duration{name:update-page-content}': ['p(95)<800'],
    'http_req_duration{name:delete-page}': ['p(95)<500'],
  },
};

export function setup(): AuthResult {
  return authenticate();
}

export default function (auth: AuthResult) {
  const headers = authHeaders(auth.accessToken);
  const baseUrl = `${config.baseUrl}/api/pagebuilder`;

  const listRes = http.get(baseUrl, { headers, tags: { name: 'list-pages' } });
  checkResponse(listRes, 'list-pages');

  const slug = `k6-page-${randomString()}`;
  const createRes = http.post(
    baseUrl,
    JSON.stringify({ title: `K6 Test Page ${randomString()}`, slug }),
    { headers, tags: { name: 'create-page' } },
  );
  checkResponse(createRes, 'create-page', 201);

  if (createRes.status === 201) {
    const created = JSON.parse(createRes.body as string);
    const pageId = created.id;

    const getRes = http.get(`${baseUrl}/${pageId}`, { headers, tags: { name: 'get-page' } });
    checkResponse(getRes, 'get-page');

    const updateContentRes = http.put(
      `${baseUrl}/${pageId}/content`,
      JSON.stringify({
        content: `<h1>Load Test Content</h1><p>Generated by k6 at ${new Date().toISOString()}</p>`,
      }),
      { headers, tags: { name: 'update-page-content' } },
    );
    checkResponse(updateContentRes, 'update-page-content');

    const deleteRes = http.del(`${baseUrl}/${pageId}`, null, {
      headers,
      tags: { name: 'delete-page' },
    });
    checkResponse(deleteRes, 'delete-page', 204);
  }

  sleep(1);
}
