import http from 'k6/http';
import { sleep } from 'k6';
import { config, defaultThresholds, loadProfiles, tlsOptions } from '../lib/config.js';
import { authenticate, authHeaders } from '../lib/auth.js';
import { checkResponse, randomString } from '../lib/helpers.js';

const profile = __ENV.K6_PROFILE || 'smoke';

export const options = {
  ...tlsOptions,
  stages: loadProfiles[profile]?.stages || loadProfiles.smoke.stages,
  thresholds: {
    ...defaultThresholds,
    'http_req_duration{name:list-pages}': ['p(95)<500'],
    'http_req_duration{name:create-page}': ['p(95)<800'],
    'http_req_duration{name:get-page}': ['p(95)<500'],
    'http_req_duration{name:update-page-content}': ['p(95)<800'],
    'http_req_duration{name:delete-page}': ['p(95)<500'],
  },
};

export function setup() {
  return authenticate();
}

export default function (auth) {
  const headers = authHeaders(auth.accessToken);
  const baseUrl = `${config.baseUrl}/api/pagebuilder`;

  // List pages
  const listRes = http.get(baseUrl, {
    headers,
    tags: { name: 'list-pages' },
  });
  checkResponse(listRes, 'list-pages');

  // Create a page
  const slug = `k6-page-${randomString()}`;
  const page = {
    title: `K6 Test Page ${randomString()}`,
    slug,
  };
  const createRes = http.post(baseUrl, JSON.stringify(page), {
    headers,
    tags: { name: 'create-page' },
  });
  checkResponse(createRes, 'create-page', 201);

  if (createRes.status === 201) {
    const created = JSON.parse(createRes.body);
    const pageId = created.id;

    // Get single page
    const getRes = http.get(`${baseUrl}/${pageId}`, {
      headers,
      tags: { name: 'get-page' },
    });
    checkResponse(getRes, 'get-page');

    // Update page content
    const updateContentRes = http.put(
      `${baseUrl}/${pageId}/content`,
      JSON.stringify({
        content: `<h1>Load Test Content</h1><p>Generated by k6 at ${new Date().toISOString()}</p>`,
      }),
      { headers, tags: { name: 'update-page-content' } },
    );
    checkResponse(updateContentRes, 'update-page-content');

    // Delete page (cleanup)
    const deleteRes = http.del(`${baseUrl}/${pageId}`, null, {
      headers,
      tags: { name: 'delete-page' },
    });
    checkResponse(deleteRes, 'delete-page', 204);
  }

  sleep(1);
}
