using FluentAssertions;
using SimpleModule.Generator.Tests.Helpers;

namespace SimpleModule.Generator.Tests;

public class RazorComponentExtensionsEmitterTests
{
    [Fact]
    public void NoModulesWithRazorComponents_MethodBodyHasNoAddAdditionalAssemblies()
    {
        var source = """
            using SimpleModule.Core;

            namespace TestApp;

            [Module("Test")]
            public class TestModule : IModule { }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var razorExt = GetGeneratedSource(result, "RazorComponentExtensions.g.cs");

        razorExt.Should().NotContain("AddAdditionalAssemblies");
        razorExt.Should().Contain("return builder;");
    }

    [Fact]
    public void GeneratedCode_UsesCorrectNamespaceAndClassName()
    {
        var source = """
            using SimpleModule.Core;

            namespace TestApp;

            [Module("Test")]
            public class TestModule : IModule { }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var razorExt = GetGeneratedSource(result, "RazorComponentExtensions.g.cs");

        razorExt.Should().Contain("namespace SimpleModule.Core;");
        razorExt.Should().Contain("public static class RazorComponentExtensions");
        razorExt
            .Should()
            .Contain("public static RazorComponentsEndpointConventionBuilder AddModuleAssemblies(");
        razorExt.Should().Contain("this RazorComponentsEndpointConventionBuilder builder)");
    }

    [Fact]
    public void AlwaysGenerated_EvenWithNoModules_FileExists()
    {
        // This test verifies the file is always emitted even when no modules have Razor components.
        var source = """
            using SimpleModule.Core;

            namespace TestApp;

            [Module("Test")]
            public class TestModule : IModule { }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        result
            .GeneratedTrees.Should()
            .Contain(t =>
                t.FilePath.EndsWith("RazorComponentExtensions.g.cs", StringComparison.Ordinal)
            );
    }

    [Fact]
    public void GeneratedCode_StartsWithAutoGeneratedComment()
    {
        var source = """
            using SimpleModule.Core;

            namespace TestApp;

            [Module("Test")]
            public class TestModule : IModule { }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var razorExt = GetGeneratedSource(result, "RazorComponentExtensions.g.cs");

        razorExt.Should().StartWith("// <auto-generated/>");
    }

    [Fact]
    public void GeneratedCode_IncludesUsingDirective()
    {
        var source = """
            using SimpleModule.Core;

            namespace TestApp;

            [Module("Test")]
            public class TestModule : IModule { }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var razorExt = GetGeneratedSource(result, "RazorComponentExtensions.g.cs");

        razorExt.Should().Contain("using Microsoft.AspNetCore.Builder;");
    }

    private static string GetGeneratedSource(
        Microsoft.CodeAnalysis.GeneratorDriverRunResult result,
        string fileName
    )
    {
        return result
            .GeneratedTrees.First(t => t.FilePath.EndsWith(fileName, StringComparison.Ordinal))
            .GetText()
            .ToString();
    }
}
