import { Trend } from 'k6/metrics';
import { defaultThresholds, loadProfiles, tlsOptions } from '../../lib/config.ts';

const profile = __ENV.K6_PROFILE || 'load';

export const endpoints: Record<string, Trend> = {
  health: new Trend('endpoint_health', true),
  alive: new Trend('endpoint_alive', true),
  token: new Trend('endpoint_token', true),
  currentUser: new Trend('endpoint_current_user', true),
  listProducts: new Trend('endpoint_list_products', true),
  createProduct: new Trend('endpoint_create_product', true),
  getProduct: new Trend('endpoint_get_product', true),
  updateProduct: new Trend('endpoint_update_product', true),
  deleteProduct: new Trend('endpoint_delete_product', true),
  listOrders: new Trend('endpoint_list_orders', true),
  createOrder: new Trend('endpoint_create_order', true),
  getOrder: new Trend('endpoint_get_order', true),
  deleteOrder: new Trend('endpoint_delete_order', true),
  listPages: new Trend('endpoint_list_pages', true),
  createPage: new Trend('endpoint_create_page', true),
  getPage: new Trend('endpoint_get_page', true),
  updatePageContent: new Trend('endpoint_update_page_content', true),
  publishPage: new Trend('endpoint_publish_page', true),
  unpublishPage: new Trend('endpoint_unpublish_page', true),
  deletePage: new Trend('endpoint_delete_page', true),
  listTags: new Trend('endpoint_list_tags', true),
  listTemplates: new Trend('endpoint_list_templates', true),
  listSettings: new Trend('endpoint_list_settings', true),
  getDefinitions: new Trend('endpoint_get_definitions', true),
  listMenus: new Trend('endpoint_list_menus', true),
  getUserSettings: new Trend('endpoint_get_user_settings', true),
  listUsers: new Trend('endpoint_list_users', true),
  queryAuditLogs: new Trend('endpoint_query_audit_logs', true),
  auditStats: new Trend('endpoint_audit_stats', true),
  listFiles: new Trend('endpoint_list_files', true),
  listFolders: new Trend('endpoint_list_folders', true),
  searchMarketplace: new Trend('endpoint_search_marketplace', true),
  listJobs: new Trend('endpoint_list_jobs', true),
  listRecurring: new Trend('endpoint_list_recurring', true),
  listFlags: new Trend('endpoint_list_flags', true),
  checkFlag: new Trend('endpoint_check_flag', true),
  listTenants: new Trend('endpoint_list_tenants', true),
  createTenant: new Trend('endpoint_create_tenant', true),
  getTenant: new Trend('endpoint_get_tenant', true),
  getTenantFeatures: new Trend('endpoint_get_tenant_features', true),
  deleteTenant: new Trend('endpoint_delete_tenant', true),
};

export const options = {
  ...tlsOptions,
  stages: loadProfiles[profile]?.stages || loadProfiles.load.stages,
  thresholds: {
    ...defaultThresholds,
    endpoint_health: ['p(95)<200'],
    endpoint_alive: ['p(95)<200'],
    endpoint_token: ['p(95)<1000'],
    endpoint_current_user: ['p(95)<500'],
    endpoint_list_products: ['p(95)<500'],
    endpoint_create_product: ['p(95)<500'],
    endpoint_get_product: ['p(95)<500'],
    endpoint_update_product: ['p(95)<500'],
    endpoint_delete_product: ['p(95)<500'],
    endpoint_list_orders: ['p(95)<500'],
    endpoint_create_order: ['p(95)<500'],
    endpoint_get_order: ['p(95)<500'],
    endpoint_delete_order: ['p(95)<500'],
    endpoint_list_pages: ['p(95)<500'],
    endpoint_create_page: ['p(95)<500'],
    endpoint_get_page: ['p(95)<500'],
    endpoint_update_page_content: ['p(95)<500'],
    endpoint_publish_page: ['p(95)<500'],
    endpoint_unpublish_page: ['p(95)<500'],
    endpoint_delete_page: ['p(95)<500'],
    endpoint_list_tags: ['p(95)<500'],
    endpoint_list_templates: ['p(95)<500'],
    endpoint_list_settings: ['p(95)<500'],
    endpoint_get_definitions: ['p(95)<500'],
    endpoint_list_menus: ['p(95)<500'],
    endpoint_get_user_settings: ['p(95)<500'],
    endpoint_list_users: ['p(95)<500'],
    endpoint_query_audit_logs: ['p(95)<500'],
    endpoint_audit_stats: ['p(95)<500'],
    endpoint_list_files: ['p(95)<500'],
    endpoint_list_folders: ['p(95)<500'],
    endpoint_search_marketplace: ['p(95)<2000'],
    endpoint_list_jobs: ['p(95)<500'],
    endpoint_list_recurring: ['p(95)<500'],
    endpoint_list_flags: ['p(95)<500'],
    endpoint_check_flag: ['p(95)<300'],
    endpoint_list_tenants: ['p(95)<500'],
    endpoint_create_tenant: ['p(95)<500'],
    endpoint_get_tenant: ['p(95)<500'],
    endpoint_get_tenant_features: ['p(95)<500'],
    endpoint_delete_tenant: ['p(95)<500'],
  },
};
